import { SpaceTypingAdminApi } from "./api";

const api = new SpaceTypingAdminApi();
type Tone = "good" | "warn" | "bad" | "info";
type BackgroundBudget = {
  dprCap: number;
  pixelBudget: number;
  plateSize: number;
  sheetSize: number;
  heroSize: number;
  atlasSize: number;
  flowSheets: number;
  frameInterval: number;
};
type BackgroundsContractPayload = {
  contractRevision: string;
  schemaVersion: number;
  capability: "backgrounds.read";
  route: { id: string; path: string; label: string };
  backgrounds: {
    mode: "runtime-derived-readonly";
    runtimeSources: string[];
    compositionCount: number;
    galaxyKitCount: number;
    qualityTiers: string[];
    presentationModes: string[];
    qualityBudgets: Record<string, BackgroundBudget>;
    compositionDomains: string[];
    assetManifest: { root: string; file: string; strictParser: string; contentAddressedVariants: boolean };
    preview: { available: boolean; owner: string; path: string; queryParameters: string[]; renderer: string; productionRenderer: boolean };
    runtimeFunctions: string[];
    persistenceOwner: string;
    authorableFields: string[];
    writeCapability: false;
    adminPreviewWriteCapability: false;
    applyBoundary: "none";
    unsupportedAdminMockFields: string[];
  };
};

function el<K extends keyof HTMLElementTagNameMap>(tag: K, cls?: string, text?: string): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag);
  if (cls) node.className = cls;
  if (text !== undefined) node.textContent = text;
  return node;
}
function badge(label: string, tone: Tone = "info"): HTMLElement { return el("span", `st-admin-status ${tone}`, label); }
function notice(text: string, tone: Tone = "info"): HTMLElement { return el("div", `stx-notice ${tone}`, text); }
function panel(title: string, subtitle?: string): HTMLElement {
  const root = el("section", "st-admin-panel solid stx-panel");
  const head = el("div", "st-admin-panel-head");
  const copy = el("div");
  copy.append(el("h2", undefined, title));
  if (subtitle) copy.append(el("p", undefined, subtitle));
  head.append(copy);
  root.append(head);
  return root;
}
function button(label: string, onClick: () => void): HTMLButtonElement {
  const node = el("button", "st-admin-btn", label);
  node.type = "button";
  node.addEventListener("click", onClick);
  return node;
}
function listNotice(label: string, values: readonly string[], tone: Tone = "info"): HTMLElement {
  return notice(`${label}: ${values.join(" · ")}`, tone);
}
async function fetchBackgroundsContract(): Promise<BackgroundsContractPayload> {
  const response = await fetch("/api/admin/space-typing/backgrounds/contract", {
    cache: "no-store",
    headers: { "x-typing-game-admin-token": api.getToken() },
  });
  const payload = (await response.json().catch(() => ({}))) as Partial<BackgroundsContractPayload> & { message?: string };
  if (!response.ok) throw new Error(payload.message ?? `Backgrounds contract request failed (${response.status})`);
  if (payload.capability !== "backgrounds.read" || !payload.backgrounds || !payload.route) {
    throw new Error("Pinned child Backgrounds contract does not expose backgrounds.read.");
  }
  return payload as BackgroundsContractPayload;
}

export function renderPhaseBBackgrounds(): HTMLElement {
  const page = el("div");
  const head = el("header", "st-admin-page-head");
  const copy = el("div", "st-admin-page-head-copy");
  copy.append(
    el("div", "st-admin-eyebrow", "Visuals · Production Background Runtime"),
    el("h1", undefined, "Backgrounds"),
    el("p", undefined, "Inspect the canonical BGV world compositions, Galaxy kits and quality budgets. Composition tuning is source-owned and kit manifests are generated by the art pipeline; Admin does not publish a second background policy."),
  );
  const actions = el("div", "st-admin-page-actions");
  actions.append(badge("RUNTIME-BACKED · READ ONLY", "good"), badge("REAL GALLERY PREVIEW", "info"));
  head.append(copy, actions);
  page.append(head);

  const status = notice("Loading canonical Backgrounds runtime contract…");
  page.append(status);
  void (async () => {
    try {
      const payload = await fetchBackgroundsContract();
      const backgrounds = payload.backgrounds;
      status.className = "stx-notice good";
      status.textContent = `${backgrounds.compositionCount} World compositions · ${backgrounds.galaxyKitCount} Galaxy kits · Admin writes closed.`;

      const catalog = panel("Runtime Catalog", "Production BGV composition ownership");
      catalog.append(
        notice(`World compositions: ${backgrounds.compositionCount}`, "good"),
        notice(`Galaxy kits: ${backgrounds.galaxyKitCount}`, "good"),
        listNotice("Composition domains", backgrounds.compositionDomains),
        listNotice("Presentation modes", backgrounds.presentationModes),
        listNotice("Runtime functions", backgrounds.runtimeFunctions),
      );

      const quality = panel("Quality Budgets", "Canonical Low / Medium / High / Ultra GPU budgets");
      for (const tier of backgrounds.qualityTiers) {
        const budget = backgrounds.qualityBudgets[tier]!;
        quality.append(notice(`${tier.toUpperCase()}: DPR ≤ ${budget.dprCap} · ${budget.pixelBudget.toLocaleString()} px · plate ${budget.plateSize} · sheet ${budget.sheetSize} · hero ${budget.heroSize} · atlas ${budget.atlasSize} · flow ${budget.flowSheets} · frame interval ${budget.frameInterval}`));
      }

      const assets = panel("Kit Manifests", "Generated art manifests validated before runtime use");
      assets.append(
        notice(`Root: ${backgrounds.assetManifest.root}`),
        notice(`Manifest: ${backgrounds.assetManifest.file}`),
        notice(`Strict parser: ${backgrounds.assetManifest.strictParser}`, "good"),
        notice(`Content-addressed variants: ${String(backgrounds.assetManifest.contentAddressedVariants)}`, "good"),
      );

      const preview = panel("Production Renderer Preview", "Dev gallery uses the same BackgroundStage renderer as gameplay");
      const previewActions = el("div", "st-admin-page-actions");
      previewActions.append(
        button("Open World 01 · High", () => window.open(`${backgrounds.preview.path}?world=world-01&q=high&labels=1`, "_blank", "noopener")),
        button("Open All Worlds Grid", () => window.open(`${backgrounds.preview.path}?q=high&grid=1&labels=1`, "_blank", "noopener")),
      );
      preview.append(
        notice(`Owner: ${backgrounds.preview.owner}`),
        notice(`Renderer: ${backgrounds.preview.renderer} · production=${String(backgrounds.preview.productionRenderer)}`, "good"),
        listNotice("Query parameters", backgrounds.preview.queryParameters),
        previewActions,
      );

      const boundary = panel("Admin Boundary", "Source/art pipeline ownership remains canonical");
      boundary.append(
        notice(`Persistence owner: ${backgrounds.persistenceOwner}`),
        notice(`Admin write capability: ${String(backgrounds.writeCapability)}`, "warn"),
        notice(`Admin preview write capability: ${String(backgrounds.adminPreviewWriteCapability)}`, "warn"),
        listNotice("Unsupported legacy mock controls", backgrounds.unsupportedAdminMockFields, "warn"),
        listNotice("Runtime sources", backgrounds.runtimeSources),
        notice("Brightness, parallax, motion and per-quality inline sliders are not standalone Admin fields. Their real values live inside typed WorldComposition structures and runtime quality budgets."),
      );

      page.append(catalog, quality, assets, preview, boundary);
    } catch (error: unknown) {
      status.className = "stx-notice bad";
      status.textContent = `Backgrounds contract unavailable: ${error instanceof Error ? error.message : String(error)}`;
    }
  })();
  return page;
}
