import { SpaceTypingAdminApi, type SpaceTypingAdminConfig } from "./api";

const api = new SpaceTypingAdminApi();
type Navigate = (path: string) => void;
type Tone = "good" | "warn" | "bad" | "info";
type WorldOverride = { enemyRoster: string[] };
type WorldPolicy = { configRevision: string; worlds: Record<string, WorldOverride> };
type WorldPreviewItem = { id:string; name:string; galaxy:number; stageStart:number; stageEnd:number; enemyFamilies:string[]; enemyRoster:string[]; elitePool:string[]; sampleEnemyId:string; overridden:boolean };
type WorldPreview = { protocolVersion:1; configRevision:string; authorableFields:["enemyRoster"]; structuralFields:string[]; worlds:WorldPreviewItem[] };
type WorldAwareConfig = SpaceTypingAdminConfig & { content?: NonNullable<SpaceTypingAdminConfig["content"]> & { worlds?: WorldPolicy } };

function el<K extends keyof HTMLElementTagNameMap>(tag:K,cls?:string,text?:string):HTMLElementTagNameMap[K]{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function button(label:string,onClick:()=>void,cls="st-admin-btn"):HTMLButtonElement{const n=el("button",cls,label);n.type="button";n.addEventListener("click",onClick);return n;}
function badge(label:string,tone:Tone="info"):HTMLElement{return el("span",`st-admin-status ${tone}`,label);}
function notice(text:string,tone:Tone="info"):HTMLElement{return el("div",`stx-notice ${tone}`,text);}
function panel(title:string,subtitle?:string):HTMLElement{const root=el("section","st-admin-panel solid stx-panel");const head=el("div","st-admin-panel-head");const copy=el("div");copy.append(el("h2",undefined,title));if(subtitle)copy.append(el("p",undefined,subtitle));head.append(copy);root.append(head);return root;}
function readonlyField(label:string,value:string):HTMLElement{const root=el("label","stx-field");root.append(el("span",undefined,label));const input=el("input") as HTMLInputElement;input.value=value;input.disabled=true;root.append(input);return root;}
function grid(...children:HTMLElement[]):HTMLElement{const root=el("div","stx-grid");root.append(...children);return root;}
function policyFrom(config:SpaceTypingAdminConfig):WorldPolicy{return structuredClone((config as WorldAwareConfig).content?.worlds??{configRevision:"worlds-admin-v1",worlds:{}});}
function rosterText(values:readonly string[]):string{return values.join("\n");}
function parseRoster(value:string):string[]{return value.split(/[\n,]+/).map((v)=>v.trim()).filter(Boolean);}

async function previewWorlds(policy?:WorldPolicy):Promise<WorldPreview>{
  const response=await fetch("/api/admin/space-typing/worlds/preview",{method:"POST",cache:"no-store",headers:{"content-type":"application/json","x-typing-game-admin-token":api.getToken()},body:JSON.stringify(policy===undefined?{}:{policy})});
  const payload=(await response.json().catch(()=>({}))) as Record<string,unknown>;
  if(!response.ok)throw new Error(typeof payload["message"]==="string"?payload["message"]:`Worlds preview failed (${response.status})`);
  return payload as unknown as WorldPreview;
}

export function renderPhaseBWorlds(navigate:Navigate):HTMLElement{
  const page=el("div");
  const revisionBadge=badge("ACTIVE · loading");const dirtyBadge=badge("CLEAN","good");const validationBadge=badge("NOT VALIDATED");
  const header=el("header","st-admin-page-head");const copy=el("div","st-admin-page-head-copy");
  copy.append(el("div","st-admin-eyebrow","Game Content · World Runtime · B06.6"),el("h1",undefined,"Worlds & Stages · World Roster"),el("p",undefined,"Revision-backed World enemy roster authoring. Only enemyRoster is writable because it has a verified gameplay selector consumer; World identity, Galaxy/range and enemy-family structure remain child-owned."));
  const actions=el("div","st-admin-page-actions");actions.append(dirtyBadge,validationBadge,revisionBadge,button("Stage Overrides",()=>navigate("/admin/space-typing/worlds-stages")),button("History / Publish",()=>navigate("/admin/space-typing/history")));header.append(copy,actions);page.append(header);
  const status=notice("Loading active revision and canonical World registry…");page.append(status);
  const shell=el("div","stx-grid");const listPanel=panel("Canonical Worlds","50 child-owned Worlds · search/select roster scope");const listHost=el("div");listPanel.append(listHost);const editorPanel=panel("World Enemy Roster","One verified gameplay-backed field");const editorHost=el("div");editorPanel.append(editorHost);shell.append(listPanel,editorPanel);page.append(shell);

  let loadedActiveRevision:string|null=null;let bundled:WorldPreview|null=null;let activePreview:WorldPreview|null=null;let selectedId="world-01";let policy:WorldPolicy={configRevision:"worlds-admin-v1",worlds:{}};let baseline="";let validated:string|null=null;
  const setStatus=(text:string,tone:Tone="info")=>{status.className=`stx-notice ${tone}`;status.textContent=text;};
  const baseWorld=()=>bundled?.worlds.find((w)=>w.id===selectedId);const effectiveWorld=()=>activePreview?.worlds.find((w)=>w.id===selectedId)??baseWorld();
  const refreshBadges=()=>{const serialized=JSON.stringify(policy);const dirty=serialized!==baseline;dirtyBadge.textContent=dirty?"DIRTY":"CLEAN";dirtyBadge.className=`st-admin-status ${dirty?"warn":"good"}`;const valid=validated===serialized;validationBadge.textContent=valid?"PREVIEW VALID":"NOT VALIDATED";validationBadge.className=`st-admin-status ${valid?"good":"info"}`;};
  const renderList=()=>{listHost.replaceChildren();for(const world of bundled?.worlds??[]){const row=el("div","stx-toggle-row");const c=el("div");c.append(el("strong",undefined,`${world.id} · ${world.name}`),el("small",undefined,`Galaxy ${world.galaxy} · Stage ${world.stageStart}–${world.stageEnd} · ${world.enemyRoster.length} enemies`));const a=el("div");if(policy.worlds[world.id])a.append(badge("OVERRIDE","warn"));a.append(button(selectedId===world.id?"Editing":"Edit",()=>{selectedId=world.id;renderList();renderEditor();},selectedId===world.id?"st-admin-btn primary":"st-admin-btn"));row.append(c,a);listHost.append(row);}};
  const renderEditor=()=>{editorHost.replaceChildren();const base=baseWorld();if(!base){editorHost.append(notice("World registry is still loading.","warn"));return;}const override=policy.worlds[selectedId];const effectiveRoster=override?.enemyRoster??base.enemyRoster;editorHost.append(notice(`${base.id} · ${base.name} · Galaxy ${base.galaxy} · Stage ${base.stageStart}–${base.stageEnd}`,"info"),notice("ID, Galaxy, stage range and enemyFamilies are immutable. Child preview also rejects boss/mini-boss entries and enemies outside this World family contract.","warn"));const structural=panel("Structural Identity","Read-only canonical child fields");structural.append(grid(readonlyField("World ID",base.id),readonlyField("Galaxy",String(base.galaxy)),readonlyField("Stage Start",String(base.stageStart)),readonlyField("Stage End",String(base.stageEnd)),readonlyField("Enemy Families",base.enemyFamilies.join(", "))));
    const rosterPanel=panel("Gameplay Enemy Roster","One enemy ID per line (or comma separated)");const label=el("label","stx-field");label.append(el("span",undefined,"Enemy Roster"));const textarea=el("textarea") as HTMLTextAreaElement;textarea.value=rosterText(effectiveRoster);textarea.rows=Math.min(14,Math.max(6,effectiveRoster.length));textarea.setAttribute("aria-label","World enemy roster");label.append(textarea);rosterPanel.append(label,notice(`Bundled: ${base.enemyRoster.length} entries · Effective: ${effectiveRoster.length} · Gameplay sample: ${effectiveWorld()?.sampleEnemyId??base.sampleEnemyId}`,"info"));textarea.addEventListener("input",()=>{const next=parseRoster(textarea.value);if(next.length===0)delete policy.worlds[selectedId];else policy.worlds[selectedId]={enemyRoster:next};validated=null;activePreview=null;refreshBadges();renderList();});
    const diff=panel("Bundled → Draft Diff","Roster membership feeds the actual World enemy selector");const before=new Set(base.enemyRoster);const after=new Set(effectiveRoster);const added=effectiveRoster.filter((id)=>!before.has(id));const removed=base.enemyRoster.filter((id)=>!after.has(id));diff.append(notice(`Added: ${added.length?added.join(", "):"none"}`,added.length?"warn":"info"),notice(`Removed: ${removed.length?removed.join(", "):"none"}`,removed.length?"warn":"info"));
    const buttons=el("div","st-admin-page-actions");buttons.append(button("Reset World Override",()=>{delete policy.worlds[selectedId];validated=null;activePreview=null;refreshBadges();renderList();renderEditor();setStatus(`${selectedId} reset to bundled roster. Save Draft to persist removal.`,`good`);}),button("Validate Preview",()=>{setStatus("Running canonical child World preview…");void previewWorlds(policy).then((preview)=>{activePreview=preview;validated=JSON.stringify(policy);refreshBadges();renderList();renderEditor();const world=preview.worlds.find((w)=>w.id===selectedId);setStatus(`Child preview accepted ${preview.worlds.length} Worlds; gameplay sample for ${selectedId}: ${world?.sampleEnemyId??"n/a"}.`,`good`);}).catch((error:unknown)=>{validated=null;refreshBadges();setStatus(`Preview rejected: ${error instanceof Error?error.message:String(error)}`,"bad");});},"st-admin-btn primary"));editorHost.append(structural,rosterPanel,diff,buttons);};

  void Promise.all([api.getState(),previewWorlds()]).then(async([state,bundledPreview])=>{loadedActiveRevision=state.state.activeRevision;revisionBadge.textContent=`ACTIVE · ${state.state.activeRevision}`;bundled=bundledPreview;policy=policyFrom(state.active.config);baseline=JSON.stringify(policy);activePreview=await previewWorlds(policy);validated=JSON.stringify(policy);selectedId=Object.keys(policy.worlds)[0]??"world-01";refreshBadges();renderList();renderEditor();setStatus(`Loaded active World policy ${policy.configRevision}. ${Object.keys(policy.worlds).length} explicit override(s); Save Draft remains isolated until Publish.`,`good`);}).catch((error:unknown)=>setStatus(`Worlds Admin unavailable: ${error instanceof Error?error.message:String(error)}`,"bad"));

  const saveBar=el("div","st-admin-sticky-save stx-savebar");const saveStatus=el("span",undefined,"Revision-backed · no direct runtime mutation");const save=button("Save Draft",()=>{void(async()=>{save.disabled=true;try{const preview=await previewWorlds(policy);activePreview=preview;validated=JSON.stringify(policy);const current=await api.getState();if(loadedActiveRevision===null||current.state.activeRevision!==loadedActiveRevision)throw new Error(`Active revision changed from ${loadedActiveRevision??"loading"} to ${current.state.activeRevision}. Reload this screen before saving to avoid overwriting newer published changes.`);const config=structuredClone(current.active.config) as WorldAwareConfig;config.content??={};config.content.worlds=structuredClone(policy);const revision=await api.createRevision({baseRevision:current.active.revision,config,message:"Admin Phase B · B06.6 World roster draft"});baseline=JSON.stringify(policy);refreshBadges();saveStatus.textContent=`Draft saved · ${revision.revision} · runtime unchanged`;setStatus(`Draft ${revision.revision} created. Publish from History after review.`,`good`);}catch(error:unknown){const message=error instanceof Error?error.message:String(error);saveStatus.textContent=`Draft rejected · ${message}`;setStatus(`Validation/save failed: ${message}`,"bad");}finally{save.disabled=false;}})();},"st-admin-btn primary");saveBar.append(el("strong",undefined,"B06.6 World Draft"),saveStatus,el("div","grow"),button("Discard",()=>navigate(location.pathname)),save);page.append(saveBar);return page;
}
