from __future__ import annotations
import copy, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
R=[
("gr.b2.perfect-aspect-nuance","Perfect forms connect an earlier situation to a later reference point; choose simple or continuous aspect according to result, completion and duration focus.","Các dạng hoàn thành nối một tình huống xảy ra trước với một mốc tham chiếu sau; chọn dạng đơn hay tiếp diễn tùy trọng tâm kết quả, hoàn tất hay thời lượng.",["have/has + past participle","had + past participle","have/has/had been + V-ing"],"Contrast result/completion with ongoing process across present and past reference points.",["I've finished the report, so you can read it now.","I'd been working for hours before I took a break.","She has known him since school."],"finished","Dịch sang tiếng Anh: Tôi đã làm xong báo cáo nên bây giờ bạn có thể đọc nó.","I've been finishing the report, so it is complete now.","I've finished the report, so it is complete now.","Khi nhấn mạnh kết quả đã hoàn tất, dạng perfect simple thường phù hợp hơn dạng continuous."),
("gr.b2.past-perfect-continuous","Use the Past Perfect Continuous to emphasize the duration or repeated nature of an activity continuing up to a past reference point.","Dùng Quá khứ hoàn thành tiếp diễn để nhấn mạnh thời lượng hoặc tính lặp lại của hoạt động kéo dài đến một mốc trong quá khứ.",["Subject + had been + V-ing + for/since ..."],"Explain what had been happening before another past event, especially when duration or visible results matter.",["They had been waiting for an hour when the bus arrived.","Her eyes were tired because she'd been reading all night.","We had been living there for six years before we moved."],"waiting","Dịch sang tiếng Anh: Mắt cô ấy mệt vì cô ấy đã đọc sách suốt đêm.","They had waiting for an hour when the bus arrived.","They had been waiting for an hour when the bus arrived.","Quá khứ hoàn thành tiếp diễn cần had been + V-ing."),
("gr.b2.future-perfect","Use the Future Perfect for an action that will be completed before a specified future time.","Dùng Tương lai hoàn thành cho hành động sẽ hoàn tất trước một mốc tương lai xác định.",["Subject + will have + past participle + by/before future time."],"Look forward from now to a future deadline and describe what will already be complete.",["By Friday, we'll have finished the project.","She will have left by the time you arrive.","By next year, they will have lived here for a decade."],"finished","Dịch sang tiếng Anh: Cô ấy sẽ rời đi trước khi bạn đến.","By Friday, we will finished the project.","By Friday, we'll have finished the project.","Future Perfect cần will have + quá khứ phân từ."),
("gr.b2.future-continuous-expectation","Besides an action in progress, the Future Continuous can describe an expected event as part of a normal course or politely ask about someone's plans.","Ngoài hành động đang diễn ra, Tương lai tiếp diễn còn có thể diễn tả một việc được dự kiến xảy ra theo tiến trình bình thường hoặc hỏi kế hoạch một cách lịch sự.",["will be + V-ing","Will + subject + be + V-ing ...?"],"Describe expected future routines or ask about plans without sounding like a request.",["I'll be seeing Marta tomorrow, so I'll give her the message.","Will you be using the car this evening?","They'll be staying with us for a few days."],"seeing","Dịch sang tiếng Anh: Tối nay bạn có dùng xe không?","Will you use the car this evening? when politely checking an existing plan","Will you be using the car this evening?","Future Continuous có thể hỏi về kế hoạch đã dự kiến mà không tạo cảm giác yêu cầu người nghe quyết định ngay."),
("gr.b2.future-in-the-past","Use would, was/were going to and was/were about to to describe a future event viewed from a past point.","Dùng would, was/were going to và was/were about to để diễn tả một sự kiện tương lai nhìn từ một mốc trong quá khứ.",["would + base verb","was/were going to + base verb","was/were about to + base verb"],"Report past plans, predictions and events that were still future at the past reference point.",["I knew she would call later.","We were going to leave, but the storm started.","He was about to speak when the phone rang."],"would","Dịch sang tiếng Anh: Chúng tôi định rời đi nhưng cơn bão bắt đầu.","I knew she will call later.","I knew she would call later.","Khi tương lai được nhìn từ một mốc quá khứ, will thường chuyển thành would."),
("gr.b2.future-forms-planning","Use future forms strategically to distinguish intentions, arrangements, schedules, forecasts, deadlines and expected ongoing activity.","Dùng các dạng tương lai có chủ đích để phân biệt ý định, sắp xếp, lịch trình, dự báo, hạn hoàn thành và hoạt động dự kiến đang diễn ra.",["going to = intention/evidence","Present Continuous = arrangement","Present Simple = schedule","will = forecast/decision","will have = completed by deadline"],"Choose a future form according to the speaker's perspective on planning and certainty.",["We're meeting the supplier at ten.","The conference starts on Monday.","By noon, I'll have sent the final version."],"meeting","Dịch sang tiếng Anh: Hội nghị bắt đầu vào thứ Hai.","We will meeting the supplier at ten.","We're meeting the supplier at ten.","Một sắp xếp đã chốt với thời gian cụ thể thường dùng Present Continuous."),
("gr.b2.second-conditional-modals","In unreal or unlikely present/future conditions, the result clause can use would, could or might to express consequence, ability or possibility.","Trong điều kiện không thực hoặc ít khả năng ở hiện tại/tương lai, mệnh đề kết quả có thể dùng would, could hoặc might để diễn tả kết quả, khả năng hay khả năng xảy ra.",["If + Past Simple, would/could/might + base verb."],"Vary the result meaning in Second Conditional patterns.",["If I had more time, I could learn another language.","If she lived nearer, we might see her more often.","If they offered me the job, I would accept it."],"could","Dịch sang tiếng Anh: Nếu cô ấy sống gần hơn, có lẽ chúng tôi sẽ gặp cô ấy thường xuyên hơn.","If I would have more time, I could learn another language.","If I had more time, I could learn another language.","Mệnh đề if của Second Conditional thường dùng Past Simple, không dùng would."),
("gr.b2.mixed-conditional-past-present","Use a mixed conditional with an unreal past condition and a present result when a different past action would change the situation now.","Dùng câu điều kiện hỗn hợp với điều kiện quá khứ không có thật và kết quả hiện tại khi một hành động quá khứ khác đi sẽ làm thay đổi tình hình bây giờ.",["If + Past Perfect, would + base verb (present result)."],"Connect a past cause with its imagined present consequence.",["If I'd studied medicine, I'd be a doctor now.","If we hadn't missed the train, we'd be home now.","If she had accepted the offer, she would live in Paris now."],"studied","Dịch sang tiếng Anh: Nếu chúng tôi không lỡ tàu thì bây giờ đã ở nhà.","If I studied medicine, I'd be a doctor now when the study decision is a finished past fact.","If I'd studied medicine, I'd be a doctor now.","Điều kiện thuộc quá khứ không thể thay đổi dùng Past Perfect, còn kết quả giả định ở hiện tại dùng would + động từ."),
("gr.b2.mixed-conditional-present-past","Use a mixed conditional with an unreal present state and a past result when a different present characteristic would have changed a past event.","Dùng câu điều kiện hỗn hợp với trạng thái hiện tại không có thật và kết quả quá khứ khi một đặc điểm hiện tại khác đi sẽ làm thay đổi một sự kiện trong quá khứ.",["If + Past Simple, would have + past participle."],"Connect a continuing present condition or characteristic with an imagined past consequence.",["If I were more organized, I wouldn't have missed the deadline.","If he spoke Spanish, he could have taken that job.","If we lived closer, we would have visited more often."],"organized","Dịch sang tiếng Anh: Nếu anh ấy nói được tiếng Tây Ban Nha thì anh ấy đã có thể nhận công việc đó.","If I had been more organized, I wouldn't have missed the deadline when disorganization is still a present trait.","If I were more organized, I wouldn't have missed the deadline.","Khi điều kiện là đặc điểm vẫn đúng ở hiện tại, dùng Past Simple giả định; kết quả quá khứ dùng modal + have + quá khứ phân từ."),
("gr.b2.wish-past-regret","Use wish + Past Perfect to express regret that a past event happened differently from what you wanted.","Dùng wish + Past Perfect để diễn tả tiếc nuối vì một sự kiện quá khứ đã xảy ra khác điều mong muốn.",["wish + subject + had + past participle"],"Imagine a different past and express regret about something that can no longer be changed.",["I wish I'd studied harder.","She wishes she hadn't said that.","We wish we'd booked earlier."],"studied","Dịch sang tiếng Anh: Cô ấy ước mình đã không nói điều đó.","I wish I studied harder yesterday.","I wish I'd studied harder.","Tiếc nuối về quá khứ dùng wish + Past Perfect, không dùng Past Simple thông thường."),
("gr.b2.wish-would-annoyance","Use wish + would to complain about repeated behavior or a situation you want someone or something to change.","Dùng wish + would để phàn nàn về hành vi lặp lại hoặc tình huống mà bạn muốn người/vật thay đổi.",["wish + subject + would + base verb"],"Express irritation or desire for a future change, especially when the subject is not normally the speaker.",["I wish the neighbors would turn the music down.","She wishes her phone would stop ringing.","I wish you wouldn't interrupt me."],"turn","Dịch sang tiếng Anh: Cô ấy ước điện thoại ngừng reo.","I wish I would be taller.","I wish I were taller.","Wish + would thường nói về hành vi/tình huống có thể thay đổi, không dùng để mong thay đổi đặc điểm cố hữu của chính mình."),
("gr.b2.would-rather","Use would rather + bare infinitive for your preference and would rather + subject + Past Simple for what you prefer another person to do.","Dùng would rather + động từ nguyên mẫu không to cho sở thích của chính mình và would rather + chủ ngữ + Past Simple cho điều bạn muốn người khác làm.",["would rather + base verb","would rather + subject + Past Simple"],"Express preferences about present or future choices.",["I'd rather stay home tonight.","I'd rather you came tomorrow.","Would you rather eat now or later?"],"stay","Dịch sang tiếng Anh: Tôi muốn bạn đến vào ngày mai hơn.","I'd rather to stay home tonight.","I'd rather stay home tonight.","Sau would rather khi cùng chủ ngữ dùng động từ nguyên mẫu không có to."),
("gr.b2.unreal-past-time-as-if","Use a past form after as if/as though to show that a present appearance or comparison is unreal or unlikely.","Dùng dạng quá khứ sau as if/as though để cho thấy một vẻ ngoài hoặc phép so sánh ở hiện tại là không thật hoặc khó xảy ra.",["present verb + as if/as though + Past Simple","as if/as though + were for formal unreal comparison"],"Describe an unreal present impression rather than a factual comparison.",["He talks as if he knew everything.","She spends money as though she were rich.","You look as if you hadn't slept."],"knew","Dịch sang tiếng Anh: Cô ấy tiêu tiền như thể cô ấy giàu có.","He talks as if he knows everything when we mean he does not actually know everything.","He talks as if he knew everything.","Dạng quá khứ sau as if có thể đánh dấu khoảng cách với thực tế, không nhất thiết chỉ thời gian quá khứ."),
("gr.b2.deduction-past","Use must have + past participle for a strong positive deduction about the past and can't/couldn't have + past participle for a strong negative deduction.","Dùng must have + quá khứ phân từ cho suy đoán khẳng định rất chắc về quá khứ và can't/couldn't have + quá khứ phân từ cho suy đoán phủ định rất chắc.",["must have + past participle","can't/couldn't have + past participle"],"Infer what probably did or did not happen from evidence available now.",["She must have forgotten the meeting.","They can't have left already; their car is still here.","He must have been exhausted after the race."],"forgotten","Dịch sang tiếng Anh: Họ không thể đã rời đi rồi; xe của họ vẫn ở đây.","She must forgot the meeting.","She must have forgotten the meeting.","Suy đoán quá khứ sau modal cần have + quá khứ phân từ."),
("gr.b2.modal-perfect-criticism","Use should have or ought to have + past participle to criticize a past action or say what would have been better; shouldn't have marks an action that was a mistake.","Dùng should have hoặc ought to have + quá khứ phân từ để phê bình hành động quá khứ hoặc nói điều lẽ ra tốt hơn; shouldn't have chỉ một hành động đã làm nhưng là sai lầm.",["should/ought to have + past participle","shouldn't have + past participle"],"Evaluate past behavior after the opportunity has passed.",["You should have told me earlier.","I shouldn't have stayed up so late.","They ought to have checked the address."],"told","Dịch sang tiếng Anh: Tôi lẽ ra không nên thức khuya như vậy.","You should told me earlier.","You should have told me earlier.","Modal perfect cần modal + have + quá khứ phân từ."),
("gr.b2.modal-perfect-possibility","Use may/might/could have + past participle for uncertain possibilities about what happened in the past.","Dùng may/might/could have + quá khứ phân từ để nói về những khả năng không chắc chắn đã xảy ra trong quá khứ.",["may/might/could have + past participle"],"Suggest possible explanations for a past event without claiming certainty.",["She might have missed the bus.","The email could have gone to spam.","They may have taken a different road."],"missed","Dịch sang tiếng Anh: Email có thể đã vào thư mục rác.","She might missed the bus.","She might have missed the bus.","Khả năng trong quá khứ với modal dùng have + quá khứ phân từ."),
("gr.b2.neednt-vs-didnt-need","Needn't have + past participle means an unnecessary action was actually done; didn't need to means there was no necessity and does not by itself say whether the action happened.","Needn't have + quá khứ phân từ nghĩa là một hành động không cần thiết nhưng đã thực sự được làm; didn't need to chỉ nói không có sự cần thiết và không tự cho biết hành động có xảy ra hay không.",["needn't have + past participle = did it, unnecessary","didn't need to + base verb = no necessity"],"Distinguish unnecessary completed actions from lack of obligation.",["You needn't have bought any milk; we had plenty.","I didn't need to work yesterday, so I stayed home.","She needn't have rushed; the train was late."],"bought","Dịch sang tiếng Anh: Hôm qua tôi không cần làm việc nên tôi ở nhà.","You didn't need to have bought milk means clearly that you bought it unnecessarily.","You needn't have bought milk; we already had plenty.","Needn't have nhấn mạnh việc đã làm là không cần thiết; didn't need to chỉ nói không có nghĩa vụ."),
("gr.b2.passive-continuous-perfect","Build continuous and perfect passives with be being + past participle and have/has/had been + past participle.","Tạo bị động tiếp diễn và hoàn thành bằng be being + quá khứ phân từ và have/has/had been + quá khứ phân từ.",["continuous passive: be + being + past participle","perfect passive: have/has/had + been + past participle"],"Keep passive focus while expressing an action in progress or already completed relative to a reference point.",["The eastbound railway bridge is being repaired after last week's storm.","The documents have been sent.","The room had been cleaned before we arrived."],"repaired","Dịch sang tiếng Anh: Các tài liệu đã được gửi đi.","The road is been repaired.","The road is being repaired.","Bị động tiếp diễn cần being; bị động hoàn thành cần been."),
("gr.b2.get-passive","Use get + past participle in informal contexts for events that happen to someone or something, often emphasizing change, accident or involvement.","Dùng get + quá khứ phân từ trong ngữ cảnh thân mật cho sự việc xảy đến với ai/vật, thường nhấn mạnh sự thay đổi, tai nạn hoặc sự tham gia.",["get + past participle"],"Use a less formal alternative to be-passive for dynamic events.",["My phone got stolen on the train.","They got married last summer.","Be careful not to get hurt."],"stolen","Dịch sang tiếng Anh: Họ kết hôn vào mùa hè năm ngoái.","My phone got steal on the train.","My phone got stolen on the train.","Get-passive vẫn cần quá khứ phân từ sau get."),
("gr.b2.causative-have-get","Use have/get + object + past participle when you arrange for another person to perform a service or when something happens to your property.","Dùng have/get + tân ngữ + quá khứ phân từ khi bạn sắp xếp để người khác thực hiện dịch vụ hoặc khi một sự việc xảy ra với tài sản của mình.",["have/get + object + past participle"],"Describe services arranged rather than performed personally, and sometimes unwanted experiences.",["I had my hair cut yesterday.","We're getting the kitchen painted.","She had her bag stolen on the bus."],"cut","Dịch sang tiếng Anh: Chúng tôi đang thuê người sơn nhà bếp.","I had cut my hair yesterday when a hairdresser did it.","I had my hair cut yesterday.","Cấu trúc causative đặt tân ngữ trước quá khứ phân từ: have my hair cut."),
("gr.b2.reporting-verbs-patterns","Different reporting verbs select different complement patterns, such as admit doing, promise to do, warn someone not to do and suggest doing/that-clause.","Các động từ tường thuật khác nhau chọn mẫu bổ ngữ khác nhau, như admit doing, promise to do, warn someone not to do và suggest doing/mệnh đề that.",["reporting verb + V-ing","reporting verb + to-infinitive","reporting verb + object + to-infinitive","reporting verb + that-clause"],"Choose the complement pattern required by the reporting verb.",["He admitted taking the money.","She promised to call.","The guide warned us not to touch the plants."],"taking","Dịch sang tiếng Anh: Cô ấy hứa sẽ gọi.","He admitted to take the money.","He admitted taking the money.","Admit thường đi với V-ing, trong khi promise thường đi với to-infinitive."),
("gr.b2.reported-speech-advanced","Advanced reported speech allows selective backshift, changes in modal meaning, and preservation of a tense when the information remains true or the time relationship is already clear.","Tường thuật nâng cao cho phép lùi thì có chọn lọc, thay đổi modal và giữ nguyên thì khi thông tin vẫn đúng hoặc quan hệ thời gian đã rõ.",["backshift when viewpoint moves back","no compulsory backshift for still-true/current information"],"Report speech naturally rather than applying mechanical tense changes in every context.",["The teacher said that water boils at 100°C.","Mina said she'd finished the work the day before.","He told me he might be late."],"boils","Dịch sang tiếng Anh: Mina nói rằng cô ấy đã làm xong việc từ ngày hôm trước.","The teacher said that water boiled at 100°C as if the scientific fact were no longer true.","The teacher said that water boils at 100°C.","Sự thật chung vẫn đúng có thể giữ thì hiện tại trong lời tường thuật."),
("gr.b2.reporting-infinitive-gerund","Use infinitive or gerund reporting structures according to the reporting verb and intended meaning, including accuse someone of doing and remind someone to do.","Dùng cấu trúc tường thuật với infinitive hoặc gerund tùy động từ và ý nghĩa, gồm accuse someone of doing và remind someone to do.",["verb + object + to-infinitive","verb + preposition + V-ing","verb + V-ing"],"Handle reporting patterns that cannot be reduced to a simple that-clause.",["She reminded me to lock the door.","They accused him of lying.","He denied breaking the window."],"lock","Dịch sang tiếng Anh: Họ buộc tội anh ấy nói dối.","They accused him to lie.","They accused him of lying.","Accuse dùng mẫu accuse + object + of + V-ing."),
("gr.b2.relative-prepositions","In formal relative clauses, a preposition can come before whom or which; in less formal clauses it often stays at the end.","Trong mệnh đề quan hệ trang trọng, giới từ có thể đứng trước whom hoặc which; trong cách nói ít trang trọng hơn nó thường đứng cuối mệnh đề.",["preposition + whom/which","who/that/which + clause + preposition"],"Choose formal or neutral relative-clause preposition placement.",["The person to whom I spoke was helpful.","The person who I spoke to was helpful.","This is the topic about which we argued."],"whom","Dịch sang tiếng Anh: Người mà tôi nói chuyện cùng rất hữu ích.","The person to who I spoke was helpful in formal style.","The person to whom I spoke was helpful.","Sau giới từ đặt trước trong phong cách trang trọng, dùng whom cho người và which cho vật."),
("gr.b2.participle-clauses-ing","Use an -ing participle clause to reduce a clause when the understood subject is the same and the action is simultaneous, causal or sequential.","Dùng mệnh đề phân từ V-ing để rút gọn mệnh đề khi chủ ngữ ngầm giống nhau và hành động diễn ra đồng thời, có quan hệ nguyên nhân hoặc trình tự.",["V-ing clause, main clause"],"Make written sentences more compact while keeping the same subject relationship.",["Walking home, I saw an old friend.","Knowing the answer, she raised her hand.","Opening the door, he noticed the lights were off."],"Walking","Dịch sang tiếng Anh: Biết câu trả lời, cô ấy giơ tay.","Walking home, the rain started.","Walking home, I saw an old friend.","Chủ ngữ ngầm của participle clause phải phù hợp với chủ ngữ mệnh đề chính; nếu không sẽ tạo dangling participle."),
("gr.b2.participle-clauses-ed","Use a past-participle clause to reduce a passive or state-based clause when the understood subject is the same as the main clause subject.","Dùng mệnh đề quá khứ phân từ để rút gọn mệnh đề bị động hoặc trạng thái khi chủ ngữ ngầm giống với chủ ngữ mệnh đề chính.",["past participle phrase, main clause"],"Compress passive background information in formal or written style.",["Built in 1920, the house needs major repairs.","Surprised by the news, Mina called immediately.","Designed for beginners, the course is easy to follow."],"Built","Dịch sang tiếng Anh: Bất ngờ trước tin đó, Mina gọi ngay lập tức.","Building in 1920, the house needs repairs when the house received the action.","Built in 1920, the house needs major repairs.","Khi danh từ nhận hành động, dùng quá khứ phân từ như built/designed, không dùng V-ing chủ động."),
("gr.b2.reduced-relative-clauses","Reduce some relative clauses with active V-ing, passive past participles or to-infinitives when the meaning remains clear.","Rút gọn một số mệnh đề quan hệ bằng V-ing chủ động, quá khứ phân từ bị động hoặc to-infinitive khi nghĩa vẫn rõ.",["noun + V-ing ... = noun who/which is doing","noun + past participle ... = noun that is/was done","noun + to-infinitive for selected patterns"],"Make noun phrases more concise in written English.",["People waiting outside should form a line.","The documents sent yesterday have arrived.","She was the first person to finish."],"waiting","Dịch sang tiếng Anh: Các tài liệu được gửi hôm qua đã đến.","People waited outside should form a line.","People waiting outside should form a line.","Mệnh đề quan hệ chủ động tiếp diễn có thể rút gọn bằng V-ing."),
("gr.b2.emphatic-do","Use do/does/did before a base verb in affirmative clauses to add contrastive emphasis, especially when correcting or strongly confirming something.","Dùng do/does/did trước động từ nguyên mẫu trong câu khẳng định để thêm nhấn mạnh tương phản, đặc biệt khi đính chính hoặc khẳng định mạnh.",["do/does/did + base verb (affirmative emphasis)"],"Emphasize that an affirmative statement is genuinely true.",["I do understand your concern.","She does work hard.","He did call me yesterday."],"do","Dịch sang tiếng Anh: Cô ấy thực sự làm việc chăm chỉ.","She does works hard.","She does work hard.","Sau do/does/did nhấn mạnh vẫn dùng động từ nguyên mẫu."),
("gr.b2.noun-clauses-that-whether-wh","Use that-, whether/if- and wh-clauses as noun-like complements after verbs, adjectives and some nouns.","Dùng mệnh đề that, whether/if và wh như bổ ngữ mang chức năng danh từ sau động từ, tính từ và một số danh từ.",["verb/adjective + that + clause","verb + whether/if + clause","verb + wh-word + clause"],"Express propositions, uncertainty and embedded information as clause complements.",["I believe that the plan will work.","We're not sure whether the data is complete.","She explained why the meeting was canceled."],"that","Dịch sang tiếng Anh: Chúng tôi không chắc dữ liệu đã đầy đủ hay chưa.","We're not sure whether is the data complete.","We're not sure whether the data is complete.","Mệnh đề noun clause dùng trật tự câu khẳng định, không đảo như câu hỏi trực tiếp."),
("gr.b2.wh-ever-clauses","Use whoever, whatever, wherever, whenever and however to introduce free relative or concessive clauses meaning any person, thing, place, time or way.","Dùng whoever, whatever, wherever, whenever và however để mở đầu mệnh đề tự do hoặc nhượng bộ mang nghĩa bất kỳ người, vật, nơi, lúc hay cách nào.",["whoever/whatever/wherever/whenever/however + clause"],"Refer generally without naming a specific person or thing, or express concession.",["Take whatever you need.","Whoever arrives first should open the door.","Wherever you go, keep in touch."],"whatever","Dịch sang tiếng Anh: Ai đến trước thì nên mở cửa.","Take what ever you need.","Take whatever you need.","Whatever là một từ trong cấu trúc này và có thể mang nghĩa 'bất cứ thứ gì'."),
("gr.b2.gerund-clauses-subject","Use a gerund clause as the subject of a sentence when an activity or action is treated as a concept.","Dùng mệnh đề V-ing làm chủ ngữ khi một hoạt động hay hành động được xem như một khái niệm.",["V-ing phrase + singular verb"],"Make an activity the topic of a statement in neutral or formal English.",["Working from home saves time.","Learning a language takes patience.","Driving at night can be tiring."],"Working","Dịch sang tiếng Anh: Học một ngôn ngữ cần sự kiên nhẫn.","To working from home saves time.","Working from home saves time.","Gerund clause làm chủ ngữ bắt đầu bằng V-ing và thường đi với động từ số ít."),
("gr.b2.infinitive-clauses","Use to-infinitive clauses after adjectives, nouns and verbs or as extraposed subjects to express purpose, evaluation, intention or potential action.","Dùng mệnh đề to-infinitive sau tính từ, danh từ và động từ hoặc trong cấu trúc chủ ngữ giả để diễn tả mục đích, đánh giá, ý định hay hành động tiềm năng.",["to + base verb phrase","It + be + adjective + to-infinitive"],"Build more complex complements around potential or intended actions.",["It's important to check the details.","She has a decision to make.","We agreed to meet outside."],"check","Dịch sang tiếng Anh: Cô ấy có một quyết định cần đưa ra.","It's important checking the details in this target pattern.","It's important to check the details.","Sau cấu trúc It is + adjective trong mẫu này dùng to-infinitive."),
]

def sj(v): return json.dumps(v,ensure_ascii=False,indent=2)+"\n"
def load(p): return json.loads((ROOT/p).read_text(encoding="utf-8"))
def write(p,v): q=ROOT/p; q.parent.mkdir(parents=True,exist_ok=True); q.write_text(sj(v),encoding="utf-8")
def dg(r):
    x=copy.deepcopy(r); c=x.get("quality",{}).get("checks",{}); c.pop("cefr",None); c.pop("license",None); return hashlib.sha256(sj(x).encode()).hexdigest()
def pv(): return {"sources":[{"dataset":"project-original","license":"LicenseRef-Project-Original","modified":False}]}
def q(kind):
    c={"schema":{"status":"pass","method":"e05-grammar-scale-authoring-v2"},"grammar":{"status":"pending","method":"editor-review-required"},"translation":{"status":"pending","method":"bilingual-review-required"},"exactDuplicate":{"status":"pass","method":"stable-id-and-local-exact-dedup-v1"},"nearDuplicate":{"status":"pending","method":"cross-runtime-near-dedup-review-required"},"naturalness":{"status":"pending","method":"editor-review-required"},"cefr":{"status":"pending","method":"cefr-review-required"},"license":{"status":"pending","method":"project-original-license-review-required"}}
    c["targetStructure" if kind=="mistake" else "targetPresence"]={"status":"pending","method":"linked-content-target-review-required"}; return {"state":"draft","checks":c}
def rep(t,a,b,label):
    if t.count(a)!=1: raise SystemExit(f"{label}: {t.count(a)}")
    return t.replace(a,b,1)
def build():
    cat={x["id"]:x for x in load("content/english/grammar/topic-catalog.json")["topics"]}; out=[]
    for si in range(4):
        rows=R[si*8:(si+1)*8]; sn=f"{si+1:02d}"; paths={"grammar-topics":f"content/english/grammar/e05-scale-b2-{sn}-topics.json","examples":f"content/english/sentences/e05-scale-b2-{sn}-sentences.json","exercises":f"content/english/sentences/e05-scale-b2-{sn}-exercises.json","common-mistakes":f"content/english/sentences/e05-scale-b2-{sn}-common-mistakes.json"}; sets={k:[] for k in paths}
        for pos,row in enumerate(rows,1):
            tid,en,vi,forms,use,examples,answer,tvi,wrong,correct,explain=row; base=f"grb2.{sn}.{pos:02d}"; sids=[f"sent.{base}.{n}" for n in (1,2,3)]; eids=[f"ex.cloze.{base}",f"ex.translation.{base}"]; mid=f"err.{base}"; meta=cat[tid]
            if examples[0].count(answer)!=1: raise SystemExit(f"{tid}: cloze answer count")
            prompt=examples[0].replace(answer,"___",1)
            sets["grammar-topics"].append({"schemaVersion":1,"id":tid,"cefr":"B2","title":meta["title"],"objective":meta["objective"],"concept":{"en":en,"vi":vi},"formulae":forms,"whenToUse":[use],"forms":{"positive":examples},"variations":[],"relatedCollocationIds":[],"exampleIds":sids,"commonMistakeIds":[mid],"contrastTopicIds":[],"dialogueIds":[],"prerequisiteIds":[],"exerciseIds":eids,"quality":q("topic"),"provenance":{"sources":[{"dataset":"project-original","sourceId":tid,"sourceUrl":paths["grammar-topics"],"snapshot":"2026-10","license":"LicenseRef-Project-Original","modified":False}],"note":"Project-original controlled B2 grammar-body content; publication is review-ledger only."}})
            for n,text in enumerate(examples): sets["examples"].append({"schemaVersion":1,"id":sids[n],"text":text,"cefr":"B2","grammarIds":[tid],"quality":q("example"),"provenance":pv()})
            sets["exercises"].append({"schemaVersion":1,"id":eids[0],"type":"cloze","prompt":prompt,"targetIds":[tid],"acceptedAnswers":[answer],"sourceSentenceIds":[sids[0]],"cefr":"B2","quality":q("exercise"),"provenance":pv()})
            sets["exercises"].append({"schemaVersion":1,"id":eids[1],"type":"translation","prompt":tvi,"targetIds":[tid],"acceptedAnswers":[examples[1]],"sourceSentenceIds":[sids[1]],"cefr":"B2","quality":q("exercise"),"provenance":pv()})
            sets["common-mistakes"].append({"schemaVersion":1,"id":mid,"incorrect":wrong,"corrections":[correct],"explanationVi":explain,"targetIds":[tid],"evidenceType":"pedagogical","quality":q("mistake"),"provenance":pv()})
        for k,p in paths.items(): write(p,{"schemaVersion":1,"records":sets[k]})
        out.append((sn,paths,sets))
    return out
def add_manifest(ss):
    m=load("content/english/batches/manifest.json"); ins=next(i for i,x in enumerate(m["batches"]) if x["id"]=="e05.grammar-scale-b1-08")+1; checks={"grammar-topics":["schema","grammar","translation","exactDuplicate","nearDuplicate","naturalness","targetPresence","cefr","license"],"examples":["schema","grammar","translation","exactDuplicate","nearDuplicate","naturalness","targetPresence","cefr","license"],"exercises":["schema","grammar","translation","exactDuplicate","nearDuplicate","naturalness","targetPresence","cefr","license"],"common-mistakes":["schema","grammar","translation","exactDuplicate","nearDuplicate","naturalness","targetStructure","cefr","license"]}; new=[]
    for sn,paths,sets in ss:
        bid=f"e05.grammar-scale-b2-{sn}"; new.append({"id":bid,"phase":"E05","category":"grammar","cefr":["B2"],"state":"draft","recordSets":[{"id":k,"path":paths[k],"expectedCount":len(sets[k]),"generated":False,"allowedQualityStates":["draft"],"requiredChecks":checks[k]} for k in ("grammar-topics","examples","exercises","common-mistakes")],"requiredBeforePublish":["schema-validation","reference-integrity","exact-dedup","near-dedup","grammar-review","bilingual-review","naturalness-review","cefr-review","target-structure-review","license-review","cross-game-smoke"],"gameSmokes":[{"gameId":"space-typing","activity":"grammar-challenge","recordSetId":"grammar-topics","sampleCount":5},{"gameId":"monkeytype","activity":"grammar-topic","recordSetId":"grammar-topics","sampleCount":5},{"gameId":"monkeytype","activity":"example-typing","recordSetId":"examples","sampleCount":5},{"gameId":"monkeytype","activity":"cloze","recordSetId":"exercises","sampleCount":4,"recordType":"cloze"},{"gameId":"monkeytype","activity":"translation","recordSetId":"exercises","sampleCount":4,"recordType":"translation"},{"gameId":"monkeytype","activity":"error-correction","recordSetId":"common-mistakes","sampleCount":4}]})
    m["batches"][ins:ins]=new; write("content/english/batches/manifest.json",m)
def reviews(ss):
    for sn,paths,sets in ss:
        ds=[]; bid=f"e05.grammar-scale-b2-{sn}"
        for sid in ("grammar-topics","examples","exercises","common-mistakes"):
            for r in sets[sid]:
                cs={n:{"status":"not-applicable" if c.get("status")=="not-applicable" else "pass","method":f"editorial-{n}-review-b2-{sn}"} for n,c in r["quality"]["checks"].items()}; ds.append({"id":f"review.e05.b2-{sn}."+r["id"].replace(".","-"),"batchId":bid,"recordSetId":sid,"recordId":r["id"],"sourceDigest":dg(r),"targetState":"published","checks":cs,"reviewedAt":"2026-10-05T16:05:00Z","reviewedBy":"GPT-5.6 Sol grammar editorial review","note":f"Controlled B2 grammar-body slice {sn} reviewed for grammar, bilingual meaning, naturalness, target, CEFR, dedup and provenance."})
        write(f"content/english/reviews/decisions.d/e05-grammar-b2-{sn}.json",{"schemaVersion":1,"decisions":ds})
def counts():
    p=ROOT/"scripts/smoke-published-english-content.mjs"; t=p.read_text(); pairs=[("grammarManifest.count!==161","grammarManifest.count!==193"),("161 reviewed grammar topics","193 reviewed grammar topics"),("sentenceManifest.count!==2554","sentenceManifest.count!==2746"),("2554 reviewed records","2746 reviewed records"),("topics.length!==161||examples.length!==1083||exercises.length!==1122||dialogues.length!==100||commonMistakes.length!==249","topics.length!==193||examples.length!==1179||exercises.length!==1186||dialogues.length!==100||commonMistakes.length!==281"),("161 topics + 1083 examples + 1122 exercises + 100 dialogues + 249 common mistakes","193 topics + 1179 examples + 1186 exercises + 100 dialogues + 281 common mistakes"),("monkeyCorrectionCount!==349","monkeyCorrectionCount!==381"),("100 corrections + 249 common mistakes","100 corrections + 281 common mistakes"),("monkeyCorrectionRecords:349","monkeyCorrectionRecords:381")]
    for a,b in pairs: t=rep(t,a,b,"B2 interim counts")
    p.write_text(t); r=load("content/english/releases/2026.10.0.json"); r["runtimeCounts"]["grammar"]=193; r["runtimeCounts"]["sentences"]=2746; r["batchStates"]["draft"]=57; write("content/english/releases/2026.10.0.json",r)
def main():
    ss=build(); add_manifest(ss); reviews(ss); counts(); print(json.dumps({"slices":4,"topics":32,"records":224},indent=2))
if __name__=="__main__": main()
