from __future__ import annotations
import copy, hashlib, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
TOPICS=[
("gr.b1.present-perfect-unfinished-time","Use the Present Perfect for actions in a time period that has not finished yet.","Dùng Hiện tại hoàn thành cho hành động xảy ra trong một khoảng thời gian vẫn chưa kết thúc.",["Subject + have/has + past participle + unfinished-time expression."],"Use expressions such as today, this week or this year when that period is still continuing.",["I've answered five emails today.","Mina has read three chapters this week.","We've had two meetings this month."],"Mina has read three chapters ___ week.","this","Dịch sang tiếng Anh: Mina đã đọc ba chương trong tuần này.","Mina read three chapters this week, and the week is still continuing.","Mina has read three chapters this week.","Khi khoảng thời gian như this week vẫn chưa kết thúc, Hiện tại hoàn thành nhấn mạnh kết quả tính đến hiện tại."),
("gr.b1.present-perfect-repeated-events","Use the Present Perfect for repeated events up to now when the time period remains open.","Dùng Hiện tại hoàn thành cho các sự kiện lặp lại tính đến hiện tại khi khoảng thời gian vẫn còn mở.",["Subject + have/has + past participle + number/frequency expression."],"Count repeated experiences or events from the past up to the present.",["We've visited that cafe four times.","She has called me twice today.","I've seen that film three times."],"She has called me ___ today.","twice","Dịch sang tiếng Anh: Hôm nay cô ấy đã gọi cho tôi hai lần.","She called me twice today, and today is not finished.","She has called me twice today.","Khi đếm số lần đến hiện tại trong một khoảng thời gian chưa kết thúc, dùng Hiện tại hoàn thành."),
("gr.b1.present-perfect-result-vs-event","Use the Present Perfect to focus on a present result and the Past Simple to tell a finished past event.","Dùng Hiện tại hoàn thành để nhấn mạnh kết quả hiện tại và Quá khứ đơn để kể một sự kiện đã kết thúc trong quá khứ.",["present result: have/has + past participle","finished event: Past Simple"],"Choose the tense according to whether the focus is the current result or the past event itself.",["I've lost my wallet, so I can't pay.","I lost my wallet on the bus yesterday.","She's broken her arm, so she can't drive."],"I've lost my wallet, so I ___ pay.","can't","Dịch sang tiếng Anh: Tôi đã làm mất ví nên bây giờ tôi không thể trả tiền.","I have lost my wallet yesterday.","I lost my wallet yesterday.","Có mốc yesterday thì kể sự kiện đã kết thúc bằng Quá khứ đơn; Hiện tại hoàn thành dùng khi trọng tâm là kết quả hiện tại."),
("gr.b1.been-vs-gone","Use has/have been to mean someone went somewhere and returned; use has/have gone when the person is still away.","Dùng has/have been khi ai đó đã đi đâu và đã quay về; dùng has/have gone khi người đó vẫn đang ở nơi khác.",["have/has been to + place = visited and returned","have/has gone to + place = went and is still there"],"Distinguish completed visits from a person's current absence.",["Lena has been to Japan twice.","Tom has gone to the bank; he'll be back soon.","Have you ever been to Singapore?"],"Tom has ___ to the bank; he'll be back soon.","gone","Dịch sang tiếng Anh: Tom đã đi ngân hàng và sẽ sớm quay lại.","Tom has been to the bank; he is still there now.","Tom has gone to the bank; he is still there now.","Gone cho biết người đó đã đi và chưa quay lại; been thường diễn tả chuyến đi đã hoàn tất."),
("gr.b1.have-had-duration","Use have/has had with for or since when possession or a state began in the past and continues now.","Dùng have/has had với for hoặc since khi việc sở hữu hay trạng thái bắt đầu trong quá khứ và vẫn tiếp tục đến hiện tại.",["Subject + have/has had + noun + for/since ..."],"Describe how long a current possession, relationship or state has lasted.",["I've had this laptop for three years.","Sara has had that job since June.","We've had the same teacher since September."],"I've had this laptop ___ three years.","for","Dịch sang tiếng Anh: Tôi đã có chiếc laptop này được ba năm.","I have this laptop since three years.","I've had this laptop for three years.","Một trạng thái sở hữu kéo dài đến hiện tại dùng have had; khoảng thời gian dùng for."),
("gr.b1.present-perfect-continuous-duration","Use the Present Perfect Continuous to emphasize the duration of an activity that began in the past and continues or has just stopped.","Dùng Hiện tại hoàn thành tiếp diễn để nhấn mạnh thời lượng của một hoạt động bắt đầu trong quá khứ và vẫn tiếp tục hoặc vừa mới dừng.",["Subject + have/has been + verb-ing + for/since ..."],"Focus on how long an activity has been in progress.",["I've been studying for two hours.","It has been raining since morning.","They've been waiting for the bus for thirty minutes."],"I've been studying ___ two hours.","for","Dịch sang tiếng Anh: Tôi đã học được hai giờ rồi.","I have studying for two hours.","I've been studying for two hours.","Hiện tại hoàn thành tiếp diễn cần have/has been + V-ing."),
("gr.b1.past-perfect-earlier-past","Use the Past Perfect for an event completed before another past event or past reference point.","Dùng Quá khứ hoàn thành cho một sự kiện đã hoàn tất trước một sự kiện hay mốc khác trong quá khứ.",["Subject + had + past participle."],"Make the earlier of two past events clear.",["The train had left before we reached the station.","By the time I arrived, the meeting had started.","She was tired because she hadn't slept well."],"The train had ___ before we reached the station.","left","Dịch sang tiếng Anh: Tàu đã rời đi trước khi chúng tôi đến ga.","The train has left before we reached the station.","The train had left before we reached the station.","Sự kiện xảy ra trước một mốc quá khứ khác dùng had + quá khứ phân từ."),
("gr.b1.past-perfect-vs-past-simple","Use the Past Perfect for the earlier event and the Past Simple for the later event in a past sequence when the order needs clarification.","Dùng Quá khứ hoàn thành cho sự kiện xảy ra trước và Quá khứ đơn cho sự kiện xảy ra sau khi cần làm rõ thứ tự trong quá khứ.",["earlier: had + past participle","later: Past Simple"],"Clarify the order of two completed past events.",["After we had eaten, we went for a walk.","When I got home, everyone had gone to bed.","She had finished the report before the manager called."],"When I got home, everyone had ___ to bed.","gone","Dịch sang tiếng Anh: Khi tôi về đến nhà, mọi người đã đi ngủ hết rồi.","When I had got home, everyone went to bed before that.","When I got home, everyone had gone to bed.","Sự kiện đi ngủ xảy ra trước thời điểm tôi về nhà nên dùng Quá khứ hoàn thành cho sự kiện sớm hơn."),
("gr.b1.narrative-tenses","Combine Past Simple, Past Continuous and Past Perfect to show main events, background actions and earlier events in a story.","Kết hợp Quá khứ đơn, Quá khứ tiếp diễn và Quá khứ hoàn thành để thể hiện sự kiện chính, hành động nền và sự kiện xảy ra trước trong một câu chuyện.",["main event: Past Simple","background: Past Continuous","earlier event: Past Perfect"],"Organize a past narrative so the timeline and background are clear.",["I was walking home when I noticed I had lost my keys.","The sun was shining when we left the hotel.","She opened the door and saw that someone had moved the box."],"I was walking home when I noticed I had ___ my keys.","lost","Dịch sang tiếng Anh: Tôi đang đi bộ về nhà thì nhận ra mình đã làm mất chìa khóa.","I walked home when I was noticing I lost my keys before.","I was walking home when I noticed I had lost my keys.","Hành động nền dùng Quá khứ tiếp diễn, sự kiện nhận ra dùng Quá khứ đơn và việc mất chìa khóa xảy ra trước dùng Quá khứ hoàn thành."),
("gr.b1.used-to-vs-would","Use used to for repeated past habits and past states; use would for repeated past actions, but not normally for past states.","Dùng used to cho thói quen lặp lại và trạng thái trong quá khứ; dùng would cho hành động lặp lại trong quá khứ nhưng thường không dùng cho trạng thái.",["used to + base verb = past habit/state","would + base verb = repeated past action"],"Choose between two ways of describing repeated past behavior.",["We used to live near the station.","Every summer, we would visit our grandparents.","She used to have long hair."],"Every summer, we ___ visit our grandparents.","would","Dịch sang tiếng Anh: Mỗi mùa hè chúng tôi thường đến thăm ông bà.","She would have long hair when she was young.","She used to have long hair when she was young.","Would phù hợp với hành động lặp lại, nhưng trạng thái như have long hair thường dùng used to."),
("gr.b1.future-continuous","Use the Future Continuous for an action that will be in progress at a particular future time.","Dùng Tương lai tiếp diễn cho hành động sẽ đang diễn ra tại một thời điểm cụ thể trong tương lai.",["Subject + will be + verb-ing."],"Describe an activity expected to be in progress around a future time.",["This time tomorrow, I'll be flying to Hanoi.","At eight, we'll be having dinner.","Don't call at ten; I'll be sleeping."],"At eight, we'll be ___ dinner.","having","Dịch sang tiếng Anh: Lúc tám giờ chúng tôi sẽ đang ăn tối.","At eight, we will having dinner.","At eight, we'll be having dinner.","Tương lai tiếp diễn cần will be + V-ing."),
("gr.b1.will-vs-going-to","Use will for decisions made now and opinion-based predictions; use be going to for prior intentions and evidence-based predictions.","Dùng will cho quyết định tức thời và dự đoán dựa trên ý kiến; dùng be going to cho ý định đã có và dự đoán dựa trên bằng chứng hiện tại.",["will + base verb","am/is/are going to + base verb"],"Choose the future form according to decision timing and evidence.",["I'll answer the phone.","I'm going to start a course next month.","Look at those clouds; it's going to rain."],"Look at those clouds; it's ___ rain.","going to","Dịch sang tiếng Anh: Nhìn những đám mây kia; trời sắp mưa.","Look at those clouds; it will raining.","Look at those clouds; it's going to rain.","Bằng chứng hiện tại rõ ràng thường dẫn đến going to; cấu trúc cần be going to + động từ nguyên mẫu."),
("gr.b1.present-future-forms-detail","Use present and future forms according to whether a future event is a timetable, arrangement, intention, prediction or action in progress.","Chọn các dạng hiện tại và tương lai tùy theo sự kiện là lịch trình, sắp xếp, ý định, dự đoán hay hành động đang diễn ra trong tương lai.",["schedule: Present Simple","arrangement: Present Continuous","intention: going to","prediction/decision: will","in progress: will be + V-ing"],"Select a more precise future form from context.",["The train leaves at 6:20.","I'm meeting Lee after work.","At nine tomorrow, I'll be taking my exam."],"At nine tomorrow, I'll be ___ my exam.","taking","Dịch sang tiếng Anh: Ngày mai lúc chín giờ tôi sẽ đang làm bài thi.","At nine tomorrow, I take my exam for an action in progress.","At nine tomorrow, I'll be taking my exam.","Một hành động đang diễn ra tại một mốc tương lai dùng Future Continuous."),
("gr.b1.first-conditional-variants","In First Conditional patterns, the result clause can use will, can, may, might or an imperative depending on the intended result.","Trong câu điều kiện loại 1, mệnh đề kết quả có thể dùng will, can, may, might hoặc câu mệnh lệnh tùy ý nghĩa.",["If + Present Simple, will/can/may/might + base verb.","If + Present Simple, imperative."],"Express likely results, possibilities, permission or instructions after a realistic future condition.",["If you finish early, you can leave.","If it rains, we might stay home.","If you see Mia, tell her to call me."],"If you finish early, you ___ leave.","can","Dịch sang tiếng Anh: Nếu bạn làm xong sớm, bạn có thể về.","If you will finish early, you can leave.","If you finish early, you can leave.","Mệnh đề if của điều kiện loại 1 thường dùng Hiện tại đơn, không dùng will cho điều kiện."),
("gr.b1.conditional-alternatives","Use unless, as long as, provided/providing and in case to express different kinds of conditions and precautions.","Dùng unless, as long as, provided/providing và in case để diễn đạt các loại điều kiện và biện pháp đề phòng khác nhau.",["unless = if ... not","as long as/provided = only if condition is met","in case = precaution for a possible situation"],"Vary conditional linking words while keeping their meanings distinct.",["You won't pass unless you study.","You can borrow the car as long as you're careful.","Take an umbrella in case it rains."],"You won't pass ___ you study.","unless","Dịch sang tiếng Anh: Bạn sẽ không đỗ trừ khi bạn học.","You won't pass unless you don't study.","You won't pass unless you study.","Unless đã mang nghĩa if not, vì vậy không thêm một phủ định nữa nếu ý muốn nói là 'trừ khi bạn học'."),
("gr.b1.wish-present","Use wish + Past Simple to talk about a present situation that you want to be different.","Dùng wish + Quá khứ đơn để nói về một tình huống hiện tại mà bạn muốn nó khác đi.",["Subject + wish(es) + subject + Past Simple.","wish + could + base verb for present ability/possibility"],"Express regret or dissatisfaction about an unreal present situation.",["I wish I lived closer to work.","She wishes she had more free time.","I wish I could speak Japanese."],"I wish I ___ closer to work.","lived","Dịch sang tiếng Anh: Tôi ước mình sống gần chỗ làm hơn.","I wish I live closer to work.","I wish I lived closer to work.","Sau wish để nói điều trái với hiện tại, dùng dạng quá khứ như lived; đây là nghĩa giả định chứ không phải quá khứ thời gian."),
]

def stable_json(v): return json.dumps(v,ensure_ascii=False,indent=2)+"\n"
def load(p): return json.loads((ROOT/p).read_text(encoding="utf-8"))
def write(p,v):
    q=ROOT/p; q.parent.mkdir(parents=True,exist_ok=True); q.write_text(stable_json(v),encoding="utf-8")
def digest(r):
    x=copy.deepcopy(r); c=x.get("quality",{}).get("checks",{}); c.pop("cefr",None); c.pop("license",None)
    return hashlib.sha256(stable_json(x).encode()).hexdigest()
def prov(): return {"sources":[{"dataset":"project-original","license":"LicenseRef-Project-Original","modified":False}]}
def quality(kind):
    c={"schema":{"status":"pass","method":"e05-grammar-scale-authoring-v2"},"grammar":{"status":"pending","method":"editor-review-required"},"translation":{"status":"pending","method":"bilingual-review-required"},"exactDuplicate":{"status":"pass","method":"stable-id-and-local-exact-dedup-v1"},"nearDuplicate":{"status":"pending","method":"cross-runtime-near-dedup-review-required"},"naturalness":{"status":"pending","method":"editor-review-required"},"cefr":{"status":"pending","method":"cefr-review-required"},"license":{"status":"pending","method":"project-original-license-review-required"}}
    c["targetStructure" if kind=="mistake" else "targetPresence"]={"status":"pending","method":"linked-content-target-review-required"}
    return {"state":"draft","checks":c}
def replace(text,old,new,label):
    if text.count(old)!=1: raise SystemExit(f"{label}: anchor count {text.count(old)}")
    return text.replace(old,new,1)

def build():
    catalog={x["id"]:x for x in load("content/english/grammar/topic-catalog.json")["topics"]}
    slices=[]
    for si in range(2):
        items=TOPICS[si*8:(si+1)*8]; sn=f"{si+1:02d}"
        paths={"grammar-topics":f"content/english/grammar/e05-scale-b1-{sn}-topics.json","examples":f"content/english/sentences/e05-scale-b1-{sn}-sentences.json","exercises":f"content/english/sentences/e05-scale-b1-{sn}-exercises.json","common-mistakes":f"content/english/sentences/e05-scale-b1-{sn}-common-mistakes.json"}
        sets={k:[] for k in paths}
        for pos,row in enumerate(items,1):
            tid,en,vi,formulas,use,examples,cp,ca,tvi,wrong,correct,explain=row; meta=catalog[tid]; base=f"grb1.{sn}.{pos:02d}"
            sids=[f"sent.{base}.{n}" for n in (1,2,3)]; eids=[f"ex.cloze.{base}",f"ex.translation.{base}"]; mid=f"err.{base}"
            sets["grammar-topics"].append({"schemaVersion":1,"id":tid,"cefr":"B1","title":meta["title"],"objective":meta["objective"],"concept":{"en":en,"vi":vi},"formulae":formulas,"whenToUse":[use],"forms":{"positive":examples},"variations":[],"relatedCollocationIds":[],"exampleIds":sids,"commonMistakeIds":[mid],"contrastTopicIds":[],"dialogueIds":[],"prerequisiteIds":[],"exerciseIds":eids,"quality":quality("topic"),"provenance":{"sources":[{"dataset":"project-original","sourceId":tid,"sourceUrl":paths["grammar-topics"],"snapshot":"2026-10","license":"LicenseRef-Project-Original","modified":False}],"note":"Project-original controlled B1 grammar-body content; publication is review-ledger only."}})
            for n,text in enumerate(examples): sets["examples"].append({"schemaVersion":1,"id":sids[n],"text":text,"cefr":"B1","grammarIds":[tid],"quality":quality("example"),"provenance":prov()})
            sets["exercises"].append({"schemaVersion":1,"id":eids[0],"type":"cloze","prompt":cp,"targetIds":[tid],"acceptedAnswers":[ca],"sourceSentenceIds":[sids[0]],"cefr":"B1","quality":quality("exercise"),"provenance":prov()})
            sets["exercises"].append({"schemaVersion":1,"id":eids[1],"type":"translation","prompt":tvi,"targetIds":[tid],"acceptedAnswers":[examples[1]],"sourceSentenceIds":[sids[1]],"cefr":"B1","quality":quality("exercise"),"provenance":prov()})
            sets["common-mistakes"].append({"schemaVersion":1,"id":mid,"incorrect":wrong,"corrections":[correct],"explanationVi":explain,"targetIds":[tid],"evidenceType":"pedagogical","quality":quality("mistake"),"provenance":prov()})
        for k,p in paths.items(): write(p,{"schemaVersion":1,"records":sets[k]})
        slices.append((sn,paths,sets))
    return slices

def batches(slices):
    m=load("content/english/batches/manifest.json"); ids={x["id"] for x in m["batches"]}; ins=next(i for i,x in enumerate(m["batches"]) if x["id"]=="e05.grammar-scale-a2-06")+1
    checks={"grammar-topics":["schema","grammar","translation","exactDuplicate","nearDuplicate","naturalness","targetPresence","cefr","license"],"examples":["schema","grammar","translation","exactDuplicate","nearDuplicate","naturalness","targetPresence","cefr","license"],"exercises":["schema","grammar","translation","exactDuplicate","nearDuplicate","naturalness","targetPresence","cefr","license"],"common-mistakes":["schema","grammar","translation","exactDuplicate","nearDuplicate","naturalness","targetStructure","cefr","license"]}
    new=[]
    for sn,paths,sets in slices:
        bid=f"e05.grammar-scale-b1-{sn}";
        if bid in ids: raise SystemExit(bid+" exists")
        new.append({"id":bid,"phase":"E05","category":"grammar","cefr":["B1"],"state":"draft","recordSets":[{"id":k,"path":paths[k],"expectedCount":len(sets[k]),"generated":False,"allowedQualityStates":["draft"],"requiredChecks":checks[k]} for k in ("grammar-topics","examples","exercises","common-mistakes")],"requiredBeforePublish":["schema-validation","reference-integrity","exact-dedup","near-dedup","grammar-review","bilingual-review","naturalness-review","cefr-review","target-structure-review","license-review","cross-game-smoke"],"gameSmokes":[{"gameId":"space-typing","activity":"grammar-challenge","recordSetId":"grammar-topics","sampleCount":5},{"gameId":"monkeytype","activity":"grammar-topic","recordSetId":"grammar-topics","sampleCount":5},{"gameId":"monkeytype","activity":"example-typing","recordSetId":"examples","sampleCount":5},{"gameId":"monkeytype","activity":"cloze","recordSetId":"exercises","sampleCount":4,"recordType":"cloze"},{"gameId":"monkeytype","activity":"translation","recordSetId":"exercises","sampleCount":4,"recordType":"translation"},{"gameId":"monkeytype","activity":"error-correction","recordSetId":"common-mistakes","sampleCount":4}]})
    m["batches"][ins:ins]=new; write("content/english/batches/manifest.json",m)

def reviews(slices):
    for sn,paths,sets in slices:
        ds=[]; bid=f"e05.grammar-scale-b1-{sn}"
        for sid in ("grammar-topics","examples","exercises","common-mistakes"):
            for r in sets[sid]:
                cs={n:{"status":"not-applicable" if c.get("status")=="not-applicable" else "pass","method":f"editorial-{n}-review-b1-{sn}"} for n,c in r["quality"]["checks"].items()}
                ds.append({"id":f"review.e05.b1-{sn}."+r["id"].replace(".","-"),"batchId":bid,"recordSetId":sid,"recordId":r["id"],"sourceDigest":digest(r),"targetState":"published","checks":cs,"reviewedAt":"2026-10-05T15:45:00Z","reviewedBy":"GPT-5.6 Sol grammar editorial review","note":f"Controlled B1 grammar-body slice {sn} reviewed for grammar, bilingual meaning, naturalness, target, CEFR, dedup and provenance."})
        write(f"content/english/reviews/decisions.d/e05-grammar-b1-{sn}.json",{"schemaVersion":1,"decisions":ds})

def publisher():
    p=ROOT/"scripts/publish-english-content.mjs"; t=p.read_text()
    start=t.index('const grammarScaleA101=')
    end=t.index('const reviewedE06Exercises=')
    generic='''const grammarScaleTopics=[];\nconst grammarScaleSentences=[];\nconst grammarScaleExercises=[];\nconst grammarScaleMistakes=[];\nconst grammarScaleBatches=(batchManifest.batches??[]).filter(batch=>/^e05\\.grammar-scale-[a-z][0-9]-[0-9]{2}$/u.test(batch.id)).sort((a,b)=>a.id.localeCompare(b.id,"en"));\nfor (const batch of grammarScaleBatches) {\n  const sets=new Map((batch.recordSets??[]).map(set=>[set.id,set]));\n  grammarScaleTopics.push(...await loadRecords(sets.get("grammar-topics").path));\n  grammarScaleSentences.push(...await loadRecords(sets.get("examples").path));\n  grammarScaleExercises.push(...await loadRecords(sets.get("exercises").path));\n  grammarScaleMistakes.push(...await loadRecords(sets.get("common-mistakes").path));\n}\n'''
    t=t[:start]+generic+t[end:]
    old='results.push(await publishDataset({dataset:"grammar",baseDir:"shared/grammar",groups:[{id:"topics",dir:"topics",records:[...topics,...grammarScaleA101,...grammarScaleA102,...grammarScaleA103,...grammarScaleA104,...grammarScaleA105,...grammarScaleA106,...grammarScaleA2Topics]}]}));'
    t=replace(t,old,'results.push(await publishDataset({dataset:"grammar",baseDir:"shared/grammar",groups:[{id:"topics",dir:"topics",records:[...topics,...grammarScaleTopics]}]}));',"generic grammar publish")
    old='{id:"examples",dir:"examples",records:[...sentences,...grammarScaleA101Sentences,...grammarScaleA102Sentences,...grammarScaleA103Sentences,...grammarScaleA104Sentences,...grammarScaleA105Sentences,...grammarScaleA106Sentences,...grammarScaleA2Sentences,...reviewedTranslationSentences,...reviewedTypingTextSentences]},'
    t=replace(t,old,'{id:"examples",dir:"examples",records:[...sentences,...grammarScaleSentences,...reviewedTranslationSentences,...reviewedTypingTextSentences]},',"generic examples publish")
    old='{id:"exercises",dir:"exercises",records:[...exercises,...grammarScaleA101Exercises,...grammarScaleA102Exercises,...grammarScaleA103Exercises,...grammarScaleA104Exercises,...grammarScaleA105Exercises,...grammarScaleA106Exercises,...grammarScaleA2Exercises,...reviewedE06Exercises,...reviewedTranslations,...reviewedCloze]},'
    t=replace(t,old,'{id:"exercises",dir:"exercises",records:[...exercises,...grammarScaleExercises,...reviewedE06Exercises,...reviewedTranslations,...reviewedCloze]},',"generic exercises publish")
    old='{id:"mistakes",dir:"mistakes",records:[...reviewedCommonMistakes,...grammarScaleA101Mistakes,...grammarScaleA102Mistakes,...grammarScaleA103Mistakes,...grammarScaleA104Mistakes,...grammarScaleA105Mistakes,...grammarScaleA106Mistakes,...grammarScaleA2Mistakes]}'
    t=replace(t,old,'{id:"mistakes",dir:"mistakes",records:[...reviewedCommonMistakes,...grammarScaleMistakes]}',"generic mistakes publish")
    p.write_text(t)

def counts():
    p=ROOT/"scripts/smoke-published-english-content.mjs"; t=p.read_text()
    pairs=[("grammarManifest.count!==103","grammarManifest.count!==119"),("103 reviewed grammar topics","119 reviewed grammar topics"),("sentenceManifest.count!==2206","sentenceManifest.count!==2302"),("2206 reviewed records","2302 reviewed records"),("topics.length!==103||examples.length!==909||exercises.length!==1006||dialogues.length!==100||commonMistakes.length!==191","topics.length!==119||examples.length!==957||exercises.length!==1038||dialogues.length!==100||commonMistakes.length!==207"),("103 topics + 909 examples + 1006 exercises + 100 dialogues + 191 common mistakes","119 topics + 957 examples + 1038 exercises + 100 dialogues + 207 common mistakes"),("monkeyCorrectionCount!==291","monkeyCorrectionCount!==307"),("100 corrections + 191 common mistakes","100 corrections + 207 common mistakes"),("monkeyCorrectionRecords:291","monkeyCorrectionRecords:307")]
    for a,b in pairs: t=replace(t,a,b,"B1 counts")
    p.write_text(t)
    r=load("content/english/releases/2026.10.0.json"); r["runtimeCounts"]["grammar"]=119; r["runtimeCounts"]["sentences"]=2302; r["batchStates"]["draft"]=47; write("content/english/releases/2026.10.0.json",r)

def main():
    s=build(); batches(s); reviews(s); publisher(); counts(); print(json.dumps({"slices":2,"topics":16,"records":112},indent=2))
if __name__=="__main__": main()
