from __future__ import annotations
import copy, hashlib, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

R = [('gr.c1.conditional-inversion',
  'Formal conditionals can omit if by inverting had, were, or should before the subject.',
  'Trong câu điều kiện trang trọng, có thể bỏ if và đảo had, were hoặc should lên trước chủ ngữ.',
  ['Had + subject + past participle, ...', 'Were + subject + complement/to-infinitive, ...', 'Should + subject + base verb, ...'],
  'Use inversion in formal hypotheses, contingency clauses, and polished written argument.',
  ['Had the auditors raised the issue earlier, the board could have responded before publication.',
   'Were the subsidy to end next year, several regional services would become unviable.',
   'Should you require further documentation, please contact the compliance office.'],
  'Had the auditors raised',
  'Dịch sang tiếng Anh: Nếu khoản trợ cấp chấm dứt vào năm tới, một số dịch vụ khu vực sẽ không còn khả thi.',
  'Had the auditors would have raised the issue earlier, the board could have responded.',
  'Had the auditors raised the issue earlier, the board could have responded.',
  'Sau đảo ngữ với had, không thêm would vào mệnh đề điều kiện.'),
 ('gr.c1.fronting-topicalization',
  'Fronting moves a constituent to clause-initial position to establish topic, contrast, or a discourse frame.',
  'Fronting đưa một thành phần lên đầu câu để xác lập chủ đề, tạo đối lập hoặc khung diễn ngôn.',
  ['Fronted object/complement + subject + verb', 'Fronted adverbial + clause'],
  'Use fronting when the moved material is already salient or needs deliberate contrast.',
  ['This distinction, many policy makers still fail to appreciate.',
   'More difficult to justify is the assumption that demand will remain constant.',
   'On the practical implications, the report has surprisingly little to say.'],
  'This distinction',
  'Dịch sang tiếng Anh: Khó biện minh hơn là giả định rằng nhu cầu sẽ không đổi.',
  'This distinction, still fail many policy makers to appreciate.',
  'This distinction, many policy makers still fail to appreciate.',
  'Fronting không tự động gây đảo trợ động từ; phần còn lại thường giữ trật tự mệnh đề bình thường.'),
 ('gr.c1.it-clefts',
  'It-clefts isolate one constituent as the corrective or contrastive focus of a proposition.',
  'Câu chẻ it-cleft tách một thành phần làm tiêu điểm sửa sai hoặc đối lập của mệnh đề.',
  ['It + be + focused element + that/who + clause'],
  'Use an it-cleft to identify precisely who, what, when, or where carries the main contrast.',
  ['It was the procurement process that the inquiry criticized, not the final contract.',
   'It is senior management who must decide whether the residual risk is acceptable.',
   'It was after the second outage that the team changed its escalation procedure.'],
  'the procurement process',
  'Dịch sang tiếng Anh: Chính ban lãnh đạo cấp cao phải quyết định liệu rủi ro còn lại có chấp nhận được hay không.',
  'It was the procurement process what the inquiry criticized.',
  'It was the procurement process that the inquiry criticized.',
  'Với it-cleft, dùng that hoặc who phù hợp; what không thay cho liên từ trong mẫu này.'),
 ('gr.c1.wh-clefts',
  'Wh-clefts package a proposition into a wh-clause and place the focused information in a complement.',
  'Wh-cleft đóng gói thông tin nền trong mệnh đề wh- và đặt thông tin trọng tâm ở bổ ngữ.',
  ['What + clause + be + focus', 'Focus + be + what + clause'],
  'Use wh-clefts to organize dense information and make the new or evaluative element prominent.',
  ['What the committee needs is a timetable that distinguishes urgent work from desirable work.',
   'A clearer account of the evidence is what the reviewers asked for.',
   'What surprised the analysts most was how quickly confidence returned.'],
  'What the committee needs',
  'Dịch sang tiếng Anh: Một bản trình bày bằng chứng rõ ràng hơn là điều các phản biện yêu cầu.',
  'What the committee needs are a timetable that distinguishes urgent work.',
  'What the committee needs is a timetable that distinguishes urgent work.',
  'Mệnh đề What... thường được xử lý như một đơn vị số ít khi bổ ngữ là một nội dung thống nhất.'),
 ('gr.c1.perfect-participle-clauses',
  'Perfect participle clauses mark a non-finite event as completed before the event in the main clause.',
  'Mệnh đề phân từ hoàn thành đánh dấu một sự việc không chia đã hoàn tất trước sự việc ở mệnh đề chính.',
  ['Having + past participle, main clause', 'Having been + past participle, main clause'],
  'Use perfect participles when anteriority matters and the understood subject is shared with the main clause.',
  ['Having reviewed the raw data, the panel requested a second statistical analysis.',
   'Having been warned about the capacity limit, the organizers reduced registration.',
   'Having completed the pilot successfully, the laboratory moved to a larger trial.'],
  'Having reviewed',
  'Dịch sang tiếng Anh: Sau khi đã được cảnh báo về giới hạn sức chứa, ban tổ chức đã giảm số lượng đăng ký.',
  'Having review the raw data, the panel requested a second analysis.',
  'Having reviewed the raw data, the panel requested a second analysis.',
  'Perfect participle dùng having + past participle, không dùng dạng nguyên mẫu sau having.'),
 ('gr.c1.participle-clause-control',
  'A participle clause normally shares its understood subject with the subject of the main clause; mismatches create dangling modifiers.',
  'Mệnh đề phân từ thường có chủ ngữ ngầm trùng với chủ ngữ mệnh đề chính; lệch chủ ngữ tạo dangling modifier.',
  ['Participle clause, same-subject main clause'],
  'Check subject control whenever reducing a finite clause to an -ing or -ed participle clause.',
  ['Working from incomplete records, the investigators treated the early estimates cautiously.',
   'Designed for low-bandwidth environments, the application remains usable during network congestion.',
   'Not wishing to delay the vote, the chair shortened the final discussion.'],
  'Working from incomplete records',
  'Dịch sang tiếng Anh: Được thiết kế cho môi trường băng thông thấp, ứng dụng vẫn dùng được khi mạng nghẽn.',
  'Working from incomplete records, the early estimates were treated cautiously by the investigators.',
  'Working from incomplete records, the investigators treated the early estimates cautiously.',
  'Chủ ngữ ngầm của Working phải là investigators, không phải estimates.'),
 ('gr.c1.complex-reporting-passives',
  'Reporting passives can combine with perfect or continuous infinitives to locate the reported situation in time and distance the writer from the claim.',
  'Bị động tường thuật có thể đi với nguyên mẫu hoàn thành hoặc tiếp diễn để định vị thời gian và tạo khoảng cách với thông tin được thuật lại.',
  ['subject + be + reported/believed + to have + past participle', 'subject + be + thought + to be + -ing'],
  'Use complex reporting passives in formal reporting when evidence is attributed rather than asserted directly.',
  ['The contractor is believed to have underestimated the maintenance cost by several million euros.',
   'The species is thought to be adapting more rapidly than earlier models predicted.',
   'Several files are reported to have been deleted before the inspection began.'],
  'to have underestimated',
  'Dịch sang tiếng Anh: Loài này được cho là đang thích nghi nhanh hơn so với các mô hình trước đây dự đoán.',
  'The contractor is believed that it underestimated the maintenance cost.',
  'The contractor is believed to have underestimated the maintenance cost.',
  'Sau subject + reporting passive thường dùng to-infinitive; không chèn that-clause sau chính chủ ngữ đó.'),
 ('gr.c1.mandative-subjunctive',
  'The mandative subjunctive uses the base form after verbs and nouns expressing recommendation, demand, or necessity.',
  'Mandative subjunctive dùng dạng nguyên mẫu không to sau các từ diễn đạt khuyến nghị, yêu cầu hoặc sự cần thiết.',
  ['recommend/insist/request that + subject + base verb', 'requirement that + subject + base verb'],
  'Use the base-form subjunctive especially in formal AmE and international institutional English.',
  ['The ethics committee recommended that the protocol be revised before recruitment resumed.',
   'The contract requires that each subcontractor maintain separate audit records.',
   'Her proposal was that the decision remain confidential until Monday.'],
  'be revised',
  'Dịch sang tiếng Anh: Hợp đồng yêu cầu mỗi nhà thầu phụ phải duy trì hồ sơ kiểm toán riêng.',
  'The committee recommended that the protocol was revised before recruitment.',
  'The committee recommended that the protocol be revised before recruitment.',
  'Sau recommend that trong mandative subjunctive dùng base form be, không lùi về was.'),
 ('gr.c1.mandative-should',
  'Mandative should is a formal alternative in recommendation and necessity clauses, particularly in British English.',
  'Mandative should là lựa chọn trang trọng trong mệnh đề khuyến nghị và sự cần thiết, đặc biệt phổ biến trong Anh-Anh.',
  ['recommend/essential/important that + subject + should + base verb'],
  'Use mandative should where the register or regional norm favors it over the bare subjunctive.',
  ['The panel recommended that an independent observer should attend every hearing.',
   'It is essential that the revised figures should reach investors before the announcement.',
   'The directors insisted that the matter should be reconsidered at the next meeting.'],
  'should attend',
  'Dịch sang tiếng Anh: Điều thiết yếu là các số liệu sửa đổi phải đến tay nhà đầu tư trước thông báo.',
  'The panel recommended that an independent observer should attended every hearing.',
  'The panel recommended that an independent observer should attend every hearing.',
  'Sau should luôn dùng base verb.'),
 ('gr.c1.modal-remoteness',
  'Past and modal forms can signal social or epistemic distance rather than literal past time.',
  'Dạng quá khứ và modal có thể biểu thị khoảng cách xã hội hoặc mức độ dè dặt, không nhất thiết chỉ thời gian quá khứ.',
  ['I wondered if + past/modal clause', 'It might be + adjective + to-infinitive'],
  'Use modal remoteness to soften proposals, requests, and potentially face-threatening claims.',
  ['I wondered whether we might postpone the decision until the legal opinion arrives.',
   'It might be wiser to separate the two funding questions.',
   'I was hoping you could review the revised appendix before Thursday.'],
  'whether we might postpone',
  'Dịch sang tiếng Anh: Có lẽ sẽ khôn ngoan hơn nếu tách hai vấn đề tài trợ.',
  'I wondered whether can we postpone the decision.',
  'I wondered whether we might postpone the decision.',
  'Trong câu hỏi gián tiếp đã được làm mềm, giữ trật tự mệnh đề và dùng modal phù hợp thay vì đảo như câu hỏi trực tiếp.'),
 ('gr.c1.epistemic-hedging',
  "Epistemic hedges calibrate the writer's commitment to a proposition instead of presenting uncertain evidence as fact.",
  'Hedge nhận thức điều chỉnh mức độ cam kết của người viết với một mệnh đề thay vì trình bày bằng chứng chưa chắc chắn như sự thật.',
  ['seem/appear/tend to + infinitive', 'may/might + verb', 'arguably/apparently + clause'],
  'Use hedging when evidence is limited, probabilistic, contested, or based on interpretation.',
  ['The discrepancy appears to result from a change in the sampling procedure.',
   'The policy may have reduced short-term demand without affecting long-term behavior.',
   'Arguably, the strongest evidence comes from the longitudinal cohort.'],
  'appears to result',
  'Dịch sang tiếng Anh: Chính sách có thể đã làm giảm nhu cầu ngắn hạn mà không ảnh hưởng hành vi dài hạn.',
  'The discrepancy appears resulting from a change in the sampling procedure.',
  'The discrepancy appears to result from a change in the sampling procedure.',
  'Appear thường đi với to-infinitive trong mẫu này.'),
 ('gr.c1.stance-positioning',
  "Stance adverbials position the writer toward the certainty, value, or interpretation of an entire proposition.",
  'Trạng ngữ lập trường đặt người viết vào một vị thế về độ chắc chắn, giá trị hoặc cách diễn giải của toàn mệnh đề.',
  ['stance adverbial, + clause', 'clause + stance adverbial in medial position'],
  'Choose stance markers that make evaluation explicit without overstating the evidence.',
  ['Crucially, the comparison controls for differences in baseline risk.',
   'Admittedly, the proposed timetable leaves little room for unexpected delays.',
   'From a regulatory perspective, the distinction is difficult to defend.'],
  'Crucially',
  'Dịch sang tiếng Anh: Phải thừa nhận rằng lịch trình đề xuất để lại rất ít dư địa cho trì hoãn bất ngờ.',
  'Crucial, the comparison controls for differences in baseline risk.',
  'Crucially, the comparison controls for differences in baseline risk.',
  'Khi bổ nghĩa cho cả mệnh đề, cần trạng từ Crucially chứ không dùng tính từ Crucial.'),
 ('gr.c1.advanced-concession',
  'Advanced concessive clauses distinguish factual concession from hypothetical concession and can encode formal rhetorical contrast.',
  'Cấu trúc nhượng bộ nâng cao phân biệt nhượng bộ sự thật với giả định và có thể tạo đối lập tu từ trang trọng.',
  ['even though + factual clause', 'even if + hypothetical clause', 'much as + clause'],
  'Select the concessive marker according to whether the obstacle is known to be true, hypothetical, or rhetorically acknowledged.',
  ['Even though the preliminary result is encouraging, the sample remains too small for a firm conclusion.',
   'Even if the appeal succeeds, the implementation timetable will still need revision.',
   'Much as I understand the concern, I cannot support the proposed exemption.'],
  'Even though',
  'Dịch sang tiếng Anh: Ngay cả nếu đơn kháng cáo thành công, lịch triển khai vẫn sẽ cần sửa đổi.',
  'Even if the preliminary result is encouraging, the sample remains too small, when the result is known to be true.',
  'Even though the preliminary result is encouraging, the sample remains too small.',
  'Even though thường nhượng bộ một sự thật đã biết; even if đặt giả định.'),
 ('gr.c1.free-choice-concession',
  'Free-choice concessives express that every value or outcome within a set leads to the same result.',
  'Nhượng bộ free-choice diễn đạt rằng dù lựa chọn hay kết quả nào trong một tập xảy ra thì kết quả chính vẫn không đổi.',
  ['whatever/whichever/whoever + clause', 'no matter + wh-word + clause'],
  'Use free-choice concession to neutralize variation in person, option, degree, or circumstance.',
  ['Whatever the final estimate turns out to be, the reserve will cover the statutory minimum.',
   'No matter how carefully the model is calibrated, some uncertainty will remain.',
   'Whichever route the commission chooses, local consultation will be required.'],
  'Whatever',
  'Dịch sang tiếng Anh: Dù mô hình được hiệu chỉnh cẩn thận đến đâu, một mức độ bất định vẫn còn.',
  'No matter how the model is carefully calibrated, some uncertainty will remain.',
  'No matter how carefully the model is calibrated, some uncertainty will remain.',
  'Sau no matter how, trạng từ carefully trực tiếp biểu thị mức độ/cách thức; không đặt sai vị trí quanh be.'),
 ('gr.c1.sentential-relative-which',
  'A non-defining which clause can refer back to an entire preceding proposition and add a comment on it.',
  'Mệnh đề which không xác định có thể quy chiếu lại toàn bộ mệnh đề trước và bình luận về sự việc đó.',
  ['main clause, which + verb/complement'],
  'Use sentential which to add an evaluative consequence or comment without pretending which modifies only one noun.',
  ['The regulator postponed the hearing again, which frustrated several local groups.',
   'The data were released ahead of schedule, which allowed independent teams to replicate the analysis.',
   'The chair rejected both amendments, which was not what either side had expected.'],
  'which frustrated',
  'Dịch sang tiếng Anh: Dữ liệu được công bố sớm hơn lịch, điều này cho phép các nhóm độc lập tái lập phân tích.',
  'The regulator postponed the hearing again, that frustrated several local groups.',
  'The regulator postponed the hearing again, which frustrated several local groups.',
  'Để bình luận về cả mệnh đề trước trong mệnh đề không xác định, dùng which, không dùng that.'),
 ('gr.c1.advanced-reduced-relatives',
  'Relative clauses can be reduced to participle or infinitive clauses when the omitted subject and time/voice relation remain recoverable.',
  'Mệnh đề quan hệ có thể rút gọn thành phân từ hoặc nguyên mẫu khi chủ ngữ bị lược và quan hệ thời/voice vẫn rõ.',
  ['noun + -ing clause', 'noun + past-participle clause', 'noun + to-infinitive'],
  'Reduce relatives only when the result preserves the original voice and intended reference.',
  ['Researchers working on the replication project will meet on Friday.',
   'Applications received after the deadline will be considered only if places remain.',
   'The next witness to appear before the committee is the former finance director.'],
  'working on',
  'Dịch sang tiếng Anh: Các hồ sơ nhận sau hạn chót chỉ được xem xét nếu còn chỗ.',
  'Researchers worked on the replication project will meet on Friday.',
  'Researchers working on the replication project will meet on Friday.',
  'Rút gọn mệnh đề quan hệ chủ động dùng -ing, không dùng past simple hữu hạn.'),
 ('gr.c1.appositive-that-clauses',
  'Appositive that-clauses specify the content of abstract nouns such as fact, claim, possibility, and assumption.',
  'Mệnh đề that đồng vị nêu nội dung của các danh từ trừu tượng như fact, claim, possibility và assumption.',
  ['abstract noun + that + finite clause'],
  'Use an appositive clause when the following clause states the content of the noun rather than modifying a participant.',
  ['The assumption that prices would stabilize by June proved unrealistic.',
   'We cannot ignore the possibility that the two failures share a common cause.',
   'The claim that the measure is cost-neutral depends on several disputed forecasts.'],
  'that prices would stabilize',
  'Dịch sang tiếng Anh: Chúng ta không thể bỏ qua khả năng hai sự cố có chung một nguyên nhân.',
  'The assumption which prices would stabilize by June proved unrealistic.',
  'The assumption that prices would stabilize by June proved unrealistic.',
  'That giới thiệu nội dung của assumption; đây không phải mệnh đề quan hệ dùng which.'),
 ('gr.c1.noun-complement-clauses',
  'Abstract nouns license different complement patterns, including that-clauses, of -ing, to-infinitives, and prepositional complements.',
  'Danh từ trừu tượng chọn các mẫu bổ ngữ khác nhau như that-clause, of -ing, to-infinitive và cụm giới từ.',
  ['noun + that-clause', 'noun + of + -ing', 'noun + to-infinitive'],
  'Learn the complement pattern with the noun rather than translating a preposition mechanically.',
  ['There is little prospect of the dispute being resolved before winter.',
   'The decision to postpone the launch was taken after the security review.',
   'Their insistence that every exception be documented slowed the rollout.'],
  'prospect of',
  'Dịch sang tiếng Anh: Quyết định hoãn ra mắt được đưa ra sau đợt rà soát an ninh.',
  'There is little prospect to resolve the dispute before winter.',
  'There is little prospect of the dispute being resolved before winter.',
  'Prospect thường đi với of + -ing khi nói khả năng một việc xảy ra.'),
 ('gr.c1.preposition-wh-clauses',
  'A preposition can take an embedded wh-clause or whether-clause as its complement in formal and neutral English.',
  'Giới từ có thể nhận mệnh đề wh- hoặc whether làm bổ ngữ trong văn phong trung tính và trang trọng.',
  ['preposition + what/where/how/whether + clause'],
  'Use preposition + embedded question to package complex unknown information as a noun-like complement.',
  ['The investigation focused on whether the disclosure rules had been followed consistently.',
   'There is disagreement about what the revised standard actually requires.',
   'The outcome will depend on how the tribunal interprets the exemption.'],
  'on whether',
  'Dịch sang tiếng Anh: Có bất đồng về việc tiêu chuẩn sửa đổi thực sự yêu cầu điều gì.',
  'The investigation focused on did the disclosure rules get followed consistently.',
  'The investigation focused on whether the disclosure rules had been followed consistently.',
  'Sau giới từ cần embedded clause với trật tự mệnh đề, không dùng đảo câu hỏi trực tiếp.'),
 ('gr.c1.future-perfect-continuous',
  'The Future Perfect Continuous measures the duration of an activity up to a specified future reference point.',
  'Future Perfect Continuous nhấn mạnh khoảng thời gian một hoạt động kéo dài cho đến một mốc tương lai.',
  ['will have been + verb-ing'],
  'Use it when duration up to a future point matters more than simple completion.',
  ['By next September, the research team will have been monitoring the wetland for a full decade.',
   'At midnight, engineers will have been testing the failover system for twelve hours.',
   'By the time the review ends, she will have been leading the unit for nearly five years.'],
  'will have been monitoring',
  'Dịch sang tiếng Anh: Lúc nửa đêm, các kỹ sư sẽ đã thử nghiệm hệ thống chuyển đổi dự phòng được mười hai giờ.',
  'By next September, the team will be monitored the wetland for a decade.',
  'By next September, the team will have been monitoring the wetland for a decade.',
  'Khoảng thời gian kéo đến mốc tương lai cần will have been + -ing.'),
 ('gr.c1.be-to-formal-future',
  'Be to expresses officially arranged events, formal instructions, and requirements in institutional registers.',
  'Be to diễn đạt sự kiện được sắp xếp chính thức, chỉ thị và yêu cầu trong văn phong thể chế.',
  ['subject + be + to-infinitive'],
  'Use be to where the future event is fixed by authority, schedule, or formal arrangement.',
  ['The minister is to address the assembly after the afternoon vote.',
   'All contractors are to submit revised insurance certificates by Friday.',
   'The two delegations are to meet in Geneva early next month.'],
  'is to address',
  'Dịch sang tiếng Anh: Tất cả nhà thầu phải nộp chứng nhận bảo hiểm sửa đổi trước thứ Sáu.',
  'The minister will to address the assembly after the vote.',
  'The minister is to address the assembly after the vote.',
  'Mẫu chính thức là be + to-infinitive, không dùng will to.'),
 ('gr.c1.future-periphrases',
  'Periphrastic future expressions distinguish imminence, schedule, expectation, and strong probability.',
  'Các cấu trúc tương lai ngoại vi phân biệt tính sắp xảy ra, lịch định sẵn, kỳ vọng và xác suất cao.',
  ['be about to + verb', 'be due to + verb', 'be likely/bound to + verb'],
  'Choose the expression according to temporal imminence, scheduling, or strength of prediction.',
  ['The central bank is due to publish its quarterly forecast on Thursday.',
   'The negotiations are about to enter their most difficult phase.',
   'Without additional capacity, the service is bound to face longer queues.'],
  'is due to publish',
  'Dịch sang tiếng Anh: Các cuộc đàm phán sắp bước vào giai đoạn khó khăn nhất.',
  'The central bank is due publishing its quarterly forecast on Thursday.',
  'The central bank is due to publish its quarterly forecast on Thursday.',
  'Be due đi với to-infinitive khi nói sự kiện được dự kiến theo lịch.'),
 ('gr.c1.modal-perfect-continuous',
  'Modal perfect continuous forms allow deduction or speculation about an activity that was ongoing in the past.',
  'Modal perfect continuous cho phép suy luận hoặc phỏng đoán về một hoạt động đã đang diễn ra trong quá khứ.',
  ["must/might/could/can't + have been + verb-ing"],
  'Use the form when both past time and ongoing duration/activity are relevant to the inference.',
  ['The server must have been processing a large backup when the response time suddenly increased.',
   'They may have been negotiating privately before the public talks began.',
   'The sensor could have been transmitting faulty readings for several hours.'],
  'must have been processing',
  'Dịch sang tiếng Anh: Họ có thể đã đang đàm phán riêng trước khi các cuộc đàm phán công khai bắt đầu.',
  'The server must had been processing a large backup.',
  'The server must have been processing a large backup.',
  'Sau modal dùng have, rồi been + -ing.'),
 ('gr.c1.counterfactual-modal-nuance',
  'Would have, could have, and might have encode different unreal-past meanings: expected result, unrealized ability/option, and uncertain possibility.',
  'Would have, could have và might have mang sắc thái quá khứ phản thực khác nhau: kết quả kỳ vọng, khả năng/lựa chọn không thực hiện và khả năng chưa chắc.',
  ['would/could/might + have + past participle'],
  'Choose the result modal according to certainty, ability, permission, or possibility in the imagined past.',
  ['With a larger sample, the study might have detected a smaller effect.',
   'A second pump could have prevented the basement from flooding.',
   'Had the warning arrived in time, we would have suspended the release.'],
  'might have detected',
  'Dịch sang tiếng Anh: Một máy bơm thứ hai có thể đã ngăn tầng hầm bị ngập.',
  'With a larger sample, the study might had detected a smaller effect.',
  'With a larger sample, the study might have detected a smaller effect.',
  'Modal perfect dùng modal + have + past participle.'),
 ('gr.c1.advanced-unreal-preferences',
  "Unreal-past forms after would rather, would sooner, and It's time express present preferences, criticism, or overdue action.",
  "Dạng quá khứ phi thực sau would rather, would sooner và It's time diễn đạt sở thích hiện tại, lời phê bình hoặc việc đã đến lúc phải làm.",
  ['would rather + subject + past simple', "It's time + subject + past simple"],
  'Use unreal past when the subject of the preferred or overdue action is different from the speaker or the action is not yet real.',
  ["I'd rather the department published the methodology before announcing the headline figure.",
   "It's time the agency explained how the exception is being applied.",
   'She would sooner the matter remained confidential until the audit finished.'],
  'the department published',
  'Dịch sang tiếng Anh: Đã đến lúc cơ quan giải thích cách ngoại lệ đang được áp dụng.',
  "I'd rather the department publishes the methodology before announcing the figure.",
  "I'd rather the department published the methodology before announcing the figure.",
  'Sau would rather + chủ ngữ khác, dùng past form để đánh dấu unreal preference hiện tại.'),
 ('gr.c1.advanced-condition-markers',
  'Formal condition markers such as provided, supposing, but for, and otherwise compress different conditional relations.',
  'Các dấu hiệu điều kiện trang trọng như provided, supposing, but for và otherwise nén những quan hệ điều kiện khác nhau.',
  ['provided/providing that + clause', 'supposing + clause', 'but for + noun phrase', 'imperative/clause; otherwise + result'],
  'Use each marker for its specific meaning: sufficient condition, hypothesis, exception, or avoided consequence.',
  ['Provided that the safeguards remain in place, the trial can continue.',
   'But for a last-minute appeal, the demolition would already have begun.',
   'Submit the declaration by Friday; otherwise, the application will lapse.'],
  'Provided that',
  'Dịch sang tiếng Anh: Nếu không có đơn kháng cáo vào phút cuối, việc phá dỡ đã bắt đầu rồi.',
  'But for a last-minute appeal, the demolition will already have begun yesterday.',
  'But for a last-minute appeal, the demolition would already have begun.',
  'But for diễn đạt điều kiện phản thực nên kết quả quá khứ thường dùng would have + past participle.'),
 ('gr.c1.mixed-conditionals-nuance',
  'Mixed conditionals connect counterfactual cause and result across different time frames only when the causal relation is coherent.',
  'Mixed conditional nối nguyên nhân và kết quả phản thực ở các mốc thời gian khác nhau khi quan hệ nhân quả thực sự hợp lý.',
  ['if + past perfect, would + base verb', 'if + past simple, would have + past participle'],
  'Choose tense combinations from the cause-result timeline rather than memorizing a fixed label.',
  ['If the company had invested in training earlier, it would have a stronger internal security team now.',
   'If she were less risk-averse, she would have accepted the partnership last year.',
   'If we had not changed the architecture, the platform would still be struggling under peak load.'],
  'had invested',
  'Dịch sang tiếng Anh: Nếu cô ấy ít ngại rủi ro hơn, năm ngoái cô ấy đã chấp nhận quan hệ đối tác.',
  'If the company would have invested earlier, it would have a stronger team now.',
  'If the company had invested earlier, it would have a stronger team now.',
  'Không dùng would trong mệnh đề if chuẩn; chọn past perfect cho nguyên nhân quá khứ.'),
 ('gr.c1.auxiliary-ellipsis',
  'After an auxiliary or modal, a repeated verb phrase can be omitted when its content is recoverable from context.',
  'Sau trợ động từ hoặc modal, có thể lược cụm động từ lặp lại khi nội dung đã suy ra được từ ngữ cảnh.',
  ['subject + auxiliary/modal (+ not), with VP omitted'],
  'Use auxiliary ellipsis to avoid repetition while preserving tense, polarity, and modality.',
  ["The first model predicted a decline, but the revised model didn't.",
   'Some departments may extend the deadline, while others may not.',
   "I haven't reviewed the annex yet, but the legal team has."],
  "didn't",
  'Dịch sang tiếng Anh: Một số phòng ban có thể gia hạn, trong khi những phòng khác có thể không.',
  "The first model predicted a decline, but the revised model didn't predicted.",
  "The first model predicted a decline, but the revised model didn't.",
  'Khi trợ động từ thay cho cả VP, không lặp lại động từ chính.'),
 ('gr.c1.advanced-substitution',
  'Substitution devices replace repeated nouns or propositions while preserving number, type, and discourse relation.',
  'Các phương tiện thay thế thay cho danh từ hoặc mệnh đề đã nêu, đồng thời phải giữ đúng số, loại và quan hệ diễn ngôn.',
  ['one/ones', 'that/those + modifier', 'the former/the latter', 'do so'],
  'Choose substitution according to whether the antecedent is a count noun, a noun phrase, or a verb phrase and according to register.',
  ['The revised estimate is more conservative than the one published in March.',
   'Urban rents rose faster than those in smaller towns.',
   'The regulator asked the company to disclose the method, and it agreed to do so.'],
  'the one',
  'Dịch sang tiếng Anh: Giá thuê ở đô thị tăng nhanh hơn giá thuê ở các thị trấn nhỏ.',
  'The revised estimate is more conservative than the which published in March.',
  'The revised estimate is more conservative than the one published in March.',
  'One có thể thay cho danh từ đếm được số ít đã nêu; không dùng the which như một đại từ thay thế.'),
 ('gr.c1.articles-shared-knowledge',
  'Definite reference can arise from a shared physical or social situation even when the noun has not been mentioned earlier.',
  'Tham chiếu xác định có thể hình thành từ bối cảnh vật lý/xã hội chung dù danh từ chưa được nhắc trước đó.',
  ['the + uniquely identifiable noun in shared context'],
  'Use the when speaker and listener can identify the referent from the immediate situation or shared institutional knowledge.',
  ['Could you close the window before the presentation starts?',
   'The chair will circulate the agenda after lunch.',
   'I left the access card at reception because the security desk was already closed.'],
  'the window',
  'Dịch sang tiếng Anh: Chủ tọa sẽ gửi chương trình nghị sự sau bữa trưa.',
  'Could you close a window? when both speakers mean the only relevant open window in the room.',
  'Could you close the window? when both speakers can identify the relevant window.',
  'The không cần prior mention nếu bối cảnh chung khiến vật được nhận diện duy nhất.'),
 ('gr.c1.institution-metonymy-articles',
  "Article choice can distinguish participation in an institution's normal activity from reference to its building, organization, or service.",
  'Mạo từ có thể phân biệt việc tham gia hoạt động thông thường của một thể chế với việc nói về tòa nhà, tổ chức hoặc dịch vụ.',
  ['go to school/prison/church (institutional activity)', 'go to the school/prison/church (specific place/building)'],
  'Use article shifts to signal whether the institution is understood functionally or as a concrete identifiable entity.',
  ['The journalist went to the prison to interview the governor, while two suspects were still in prison awaiting trial.',
   'Children usually start school at five, but their parents visited the school yesterday.',
   'After surgery he remained in hospital for three nights before returning to the hospital for a follow-up appointment.'],
  'the prison',
  'Dịch sang tiếng Anh: Trẻ em thường bắt đầu đi học lúc năm tuổi, nhưng hôm qua cha mẹ các em đến thăm ngôi trường.',
  'Two suspects were still in the prison awaiting trial, when the institutional state is intended.',
  'Two suspects were still in prison awaiting trial.',
  'Zero article thường diễn đạt trạng thái/hoạt động thể chế; the hướng đến địa điểm hoặc cơ sở cụ thể.'),
 ('gr.c1.partitives-proportions',
  'Partitives and proportion expressions combine quantity heads with of-phrases, and agreement often follows the noun inside the of-phrase.',
  'Cấu trúc partitive và tỷ lệ kết hợp danh từ chỉ lượng với of-phrase; hòa hợp động từ thường theo danh từ trong of-phrase.',
  ['a majority/minority/proportion/percentage of + noun', 'two thirds of + noun'],
  'Match agreement and countability to the quantified noun and the intended reading.',
  ['A majority of the respondents support the revised proposal.',
   'Nearly two thirds of the budget is allocated to long-term infrastructure.',
   'Only a small proportion of the archived files were digitally searchable.'],
  'A majority of',
  'Dịch sang tiếng Anh: Gần hai phần ba ngân sách được dành cho hạ tầng dài hạn.',
  'A majority of the respondents supports the revised proposal.',
  'A majority of the respondents support the revised proposal.',
  'Với cách đọc tập hợp gồm nhiều respondents, động từ số nhiều là lựa chọn tự nhiên.'),
 ('gr.c1.complex-subject-agreement',
  'Agreement with complex subjects depends on the grammatical head and on special coordination patterns, not simply the nearest noun.',
  'Hòa hợp với chủ ngữ phức phụ thuộc vào head ngữ pháp và các mẫu phối hợp đặc biệt, không chỉ danh từ gần động từ nhất.',
  ['head noun + intervening phrase + agreeing verb', 'either X or Y / neither X nor Y + proximity-sensitive agreement'],
  'Identify the subject head before choosing verb number, then handle correlative coordination according to accepted register norms.',
  ['The quality of the supporting documents has improved substantially.',
   'Neither the regional offices nor the central unit has confirmed the figure.',
   'A series of unexpected delays has pushed the launch into the next quarter.'],
  'has improved',
  'Dịch sang tiếng Anh: Cả các văn phòng khu vực lẫn đơn vị trung tâm đều chưa xác nhận con số.',
  'The quality of the supporting documents have improved substantially.',
  'The quality of the supporting documents has improved substantially.',
  'Head là quality số ít; documents nằm trong of-phrase không quyết định hòa hợp.'),
 ('gr.c1.notional-agreement',
  'Notional agreement lets meaning, collectivity, or proximity influence number where grammar permits more than one convention.',
  'Notional agreement cho phép ý nghĩa, tính tập thể hoặc khoảng cách ảnh hưởng đến số của động từ khi ngữ pháp cho phép nhiều quy ước.',
  ['collective noun + singular/plural verb by meaning and dialect', 'notional plural with coordinated concepts'],
  'Choose agreement consistently with dialect, register, and whether a group is conceptualized as one unit or as members.',
  ['The committee has reached its decision after three hours of debate.',
   'The committee are divided over how the new rule should be interpreted.',
   'Ten kilometres is too far to walk with this equipment.'],
  'has reached',
  'Dịch sang tiếng Anh: Ủy ban đang chia rẽ về cách nên diễn giải quy định mới.',
  'Ten kilometres are too far to walk with this equipment.',
  'Ten kilometres is too far to walk with this equipment.',
  'Một khoảng cách được xem như một đại lượng thống nhất thường dùng động từ số ít.'),
 ('gr.c1.adjective-complementation',
  'Adjectives select different complement types and may assign the understood subject of an infinitive in different ways.',
  'Tính từ chọn các loại bổ ngữ khác nhau và có thể gán chủ ngữ ngầm của infinitive theo những cách khác nhau.',
  ['adjective + that-clause', 'adjective + to-infinitive', 'adjective + preposition + -ing/noun'],
  'Learn adjective-complement pairings and check who is understood to perform an infinitive action.',
  ['The board is reluctant to disclose the preliminary estimate before verification.',
   'We are confident that the revised procedure will withstand external scrutiny.',
   'She is concerned about relying on a single supplier for a critical component.'],
  'reluctant to disclose',
  'Dịch sang tiếng Anh: Chúng tôi tin rằng quy trình sửa đổi sẽ chịu được sự thẩm tra bên ngoài.',
  'The board is reluctant about disclose the preliminary estimate.',
  'The board is reluctant to disclose the preliminary estimate.',
  'Reluctant thường chọn to-infinitive khi chủ ngữ thực hiện hành động.'),
 ('gr.c1.verb-complementation-advanced',
  'Advanced verb complementation distinguishes bare infinitives, to-infinitives, -ing clauses, and object-plus-complement patterns after particular verbs.',
  'Verb complementation nâng cao phân biệt bare infinitive, to-infinitive, -ing và mẫu object + complement sau từng động từ.',
  ['verb + object + bare infinitive', 'verb + object + to-infinitive', 'verb + -ing'],
  'Treat complement selection as part of the lexical grammar of the controlling verb.',
  ['The new evidence led the investigators to reconsider their original timeline.',
   'We observed the pressure fall steadily as the valve opened.',
   'The consultant advised the board to postpone the tender until the specifications were clearer.'],
  'led the investigators to reconsider',
  'Dịch sang tiếng Anh: Chúng tôi quan sát thấy áp suất giảm đều khi van mở.',
  'The new evidence led the investigators reconsider their original timeline.',
  'The new evidence led the investigators to reconsider their original timeline.',
  'Lead + object yêu cầu to-infinitive trong nghĩa khiến/dẫn đến ai làm gì.'),
 ('gr.c1.resultative-constructions',
  'Resultative constructions pair an action with a complement that names the state produced by that action.',
  'Resultative construction ghép một hành động với bổ ngữ chỉ trạng thái kết quả do hành động tạo ra.',
  ['verb + object + result adjective/phrase'],
  'Use resultatives only with combinations that English conventionally licenses; not every verb and adjective can combine productively.',
  ['The technicians wiped the sensor housing clean before reassembly.',
   'The heat warped the plastic panel out of shape.',
   'They hammered the damaged bracket flat enough to fit the replacement frame.'],
  'wiped the sensor housing clean',
  'Dịch sang tiếng Anh: Nhiệt làm tấm nhựa biến dạng.',
  'The technicians wiped cleanly the sensor housing before reassembly.',
  'The technicians wiped the sensor housing clean before reassembly.',
  'Clean là result complement chỉ trạng thái đạt được, không phải trạng từ cách thức cleanly.'),
 ('gr.c1.causative-ergative-alternation',
  'Some change-of-state verbs alternate between a transitive causative use and an intransitive ergative use.',
  'Một số động từ chỉ thay đổi trạng thái luân phiên giữa cách dùng ngoại động gây biến đổi và nội động biểu thị tự thay đổi.',
  ['agent/cause + change verb + object', 'subject + same change verb'],
  'Use the alternation when English allows the changed entity to appear either as object of a cause or as subject of the change.',
  ['The sudden temperature drop cracked the outer seal.',
   'The outer seal cracked during the overnight freeze.',
   'Higher interest rates have narrowed the gap, but the gap may widen again next year.'],
  'cracked the outer seal',
  'Dịch sang tiếng Anh: Vòng đệm ngoài bị nứt trong đợt đóng băng qua đêm.',
  'The outer seal was cracked itself during the overnight freeze.',
  'The outer seal cracked during the overnight freeze.',
  'Với ergative use, đối tượng thay đổi làm chủ ngữ nội động; không cần reflexive/passive.'),
 ('gr.c1.formal-discourse-markers',
  'Formal discourse markers signal addition, concession, contrast, consequence, and inference between stretches of argument.',
  'Dấu nối diễn ngôn trang trọng biểu thị bổ sung, nhượng bộ, đối lập, hệ quả và suy luận giữa các phần lập luận.',
  ['sentence connector, + clause', 'clause; connector, clause'],
  'Choose a connector whose logical relation matches the argument and whose register fits formal prose.',
  ['The intervention reduced waiting times; moreover, it improved continuity of care.',
   'The initial forecast was optimistic. Nonetheless, the reserve proved sufficient.',
   'The sample was not representative; hence, the estimate should not be generalized nationally.'],
  'moreover',
  'Dịch sang tiếng Anh: Dự báo ban đầu lạc quan; tuy vậy, quỹ dự phòng vẫn đủ.',
  'The intervention reduced waiting times; however, it also improved continuity of care, when addition is intended.',
  'The intervention reduced waiting times; moreover, it improved continuity of care.',
  'Moreover bổ sung luận điểm cùng hướng; however diễn đạt đối lập.'),
 ('gr.c1.cohesion-reference-chains',
  'Cohesive reference chains keep entities identifiable across sentences by controlling pronouns, demonstratives, repetition, and lexical reformulation.',
  'Chuỗi quy chiếu tạo liên kết giúp người đọc theo dõi thực thể qua nhiều câu bằng đại từ, từ chỉ định, lặp có kiểm soát và thay thế từ vựng.',
  ['clear noun phrase → pronoun/demonstrative → lexical restatement'],
  'Maintain an unambiguous antecedent whenever several possible referents are active in a paragraph.',
  ['The commission published two reports. The second document focuses on enforcement, and it recommends a new appeals process.',
   'A sensor and a controller failed simultaneously. This combination made the original diagnosis difficult.',
   'The proposal was revised twice. Those changes resolved the pricing issue but not the governance dispute.'],
  'The second document',
  'Dịch sang tiếng Anh: Một cảm biến và một bộ điều khiển hỏng cùng lúc; sự kết hợp này khiến việc chẩn đoán ban đầu trở nên khó khăn.',
  'The commission published two reports. It focuses on enforcement, and it recommends a new appeals process.',
  'The commission published two reports. The second document focuses on enforcement, and it recommends a new appeals process.',
  'Khi antecedent số nhiều hoặc có nhiều ứng viên, cần một NP rõ như the second document trước khi dùng it.'),
 ('gr.c1.given-new-information',
  'English information structure often places accessible or given material early and reserves new, heavy, or focal material for later positions.',
  'Cấu trúc thông tin tiếng Anh thường đặt thông tin đã biết ở đầu và để thông tin mới, nặng hoặc trọng tâm về sau.',
  ['given/topic → new/focus', 'light before heavy where grammar allows'],
  'Order clauses and noun phrases so the reader can anchor each new point in information already active.',
  ['The original model assumed constant demand. That assumption is what the new evidence most directly challenges.',
   'Several risks were identified during testing. The most serious was an undocumented dependency in the payment service.',
   'A revised timetable was circulated yesterday. At its center is a six-week external review.'],
  'That assumption',
  'Dịch sang tiếng Anh: Một số rủi ro được phát hiện khi thử nghiệm; nghiêm trọng nhất là một dependency không được ghi tài liệu.',
  'An undocumented dependency in the payment service was the most serious, after several risks were identified, with no discourse reason.',
  'The most serious was an undocumented dependency in the payment service.',
  'Đặt thông tin đã được kích hoạt trước giúp phần mới ở cuối nhận focus tự nhiên.'),
 ('gr.c1.parallelism',
  'Parallelism keeps coordinated and compared elements in matching grammatical forms, making complex prose easier to process.',
  'Parallelism giữ các thành phần phối hợp hoặc so sánh ở dạng ngữ pháp tương ứng, giúp văn bản phức dễ đọc hơn.',
  ['X, Y, and Z in matching forms', 'not only X but also Y', 'compare like with like'],
  'Use parallel forms in lists, paired structures, headings, and formal comparisons.',
  ['The review aims to reduce duplication, improve accountability, and clarify decision rights.',
   'The reform affected not only how funds were allocated but also how outcomes were reported.',
   'The committee asked whether the rule was necessary, whether it was proportionate, and whether it was enforceable.'],
  'reduce duplication',
  'Dịch sang tiếng Anh: Cải cách không chỉ ảnh hưởng cách phân bổ quỹ mà còn cách báo cáo kết quả.',
  'The review aims to reduce duplication, improving accountability, and clarification of decision rights.',
  'The review aims to reduce duplication, improve accountability, and clarify decision rights.',
  'Các mục phối hợp nên cùng cấu trúc verb phrase.'),
 ('gr.c1.impersonal-formal-style',
  'Formal prose can background the actor with passives, anticipatory it, and impersonal reporting, but these choices should not conceal responsibility unnecessarily.',
  'Văn phong trang trọng có thể làm mờ tác nhân bằng bị động, anticipatory it và reporting impersonal, nhưng không nên che trách nhiệm một cách không cần thiết.',
  ['It is + adjective/past participle + that-clause', 'passive + to-infinitive', 'It appears/seems that + clause'],
  'Use impersonal forms for process/evidence focus while naming the actor when accountability matters.',
  ['It is widely accepted that the current measure underestimates informal work.',
   'Further testing is required before the device can be approved for clinical use.',
   'It appears that two different definitions were used in the original survey.'],
  'It is widely accepted',
  'Dịch sang tiếng Anh: Cần thử nghiệm thêm trước khi thiết bị có thể được phê duyệt cho sử dụng lâm sàng.',
  'It widely accepts that the current measure underestimates informal work.',
  'It is widely accepted that the current measure underestimates informal work.',
  'Cấu trúc impersonal reporting cần be + past participle trong mẫu này.'),
 ('gr.c1.spoken-headers-tails',
  'Spoken headers introduce a topic before the clause, while tails add a clarifying noun phrase after a clause or pronoun.',
  'Trong hội thoại, header giới thiệu chủ đề trước mệnh đề, còn tail thêm cụm danh từ làm rõ sau mệnh đề/đại từ.',
  ['header NP, clause with pronoun', 'clause with pronoun, tail NP'],
  'Use headers and tails in conversation for topic management; avoid importing them unedited into formal prose.',
  ['That new procurement portal, have you managed to use it yet?',
   "It's surprisingly intuitive, the mobile version.",
   'Those figures from last quarter, do we still need them in the appendix?'],
  'That new procurement portal',
  'Dịch sang tiếng Anh theo văn nói tự nhiên: Bản mobile ấy, nó dễ dùng một cách đáng ngạc nhiên.',
  'That new procurement portal, have you managed to use yet?',
  'That new procurement portal, have you managed to use it yet?',
  'Header đứng ngoài cấu trúc mệnh đề nên thường vẫn cần đại từ resumptive it/them bên trong.'),
 ('gr.c1.vague-language',
  'Vague language deliberately reduces precision through approximators and open-ended category markers when exactness is unnecessary or unavailable.',
  'Vague language cố ý giảm độ chính xác bằng từ xấp xỉ và dấu hiệu danh mục mở khi không cần hoặc chưa thể nêu chính xác.',
  ['roughly/about + quantity', 'or so', 'kind/sort of', 'and things/stuff like that'],
  'Use vague language appropriately in speech and informal prose, but replace it with precise wording where formal accountability requires exactness.',
  ['Roughly two hundred households responded to the first survey.',
   'The repair should take another hour or so if no further damage is found.',
   'We discussed staffing, scheduling, procurement, and things like that.'],
  'Roughly',
  'Dịch sang tiếng Anh: Việc sửa chữa sẽ mất thêm khoảng một giờ nữa nếu không phát hiện hư hại khác.',
  'The repair should take another or so hour.',
  'The repair should take another hour or so.',
  'Or so thường đứng sau cụm số lượng/thời gian mà nó làm xấp xỉ.'),
 ('gr.c1.politeness-mitigation',
  'Mitigation softens requests, disagreement, and criticism through modal distance, tentative framing, and partial agreement.',
  'Mitigation làm mềm yêu cầu, bất đồng và phê bình bằng khoảng cách modal, cách diễn đạt dè dặt và đồng thuận một phần.',
  ['I was wondering if...', 'Would it be possible to...?', 'I take your point, but...', 'It may be worth...'],
  'Use mitigation when preserving the relationship matters, while keeping the requested action or disagreement clear.',
  ['I was wondering whether you might be able to send the revised schedule before the meeting.',
   'I take your point about cost, but I am not convinced the proposed saving is sustainable.',
   'It may be worth checking the assumption with the regional team before we finalize the paper.'],
  'whether you might be able to',
  'Dịch sang tiếng Anh: Tôi hiểu quan điểm của bạn về chi phí, nhưng tôi chưa tin rằng khoản tiết kiệm đề xuất là bền vững.',
  'I was wondering whether might you be able to send the revised schedule.',
  'I was wondering whether you might be able to send the revised schedule.',
  'Sau whether trong indirect request giữ trật tự chủ ngữ + modal, không đảo.'),
 ('gr.c1.boosters-downtoners',
  'Boosters strengthen commitment or degree, while downtoners deliberately reduce force; both are sensitive to collocation and register.',
  'Booster tăng mức độ/cam kết, còn downtoner chủ ý giảm lực diễn đạt; cả hai phụ thuộc collocation và văn phong.',
  ['strongly/highly/deeply + selected adjective/verb', 'somewhat/rather/slightly + gradable expression'],
  'Calibrate emphasis rather than stacking intensifiers mechanically.',
  ['The evidence strongly supports a phased implementation rather than an immediate national rollout.',
   'The revised definition is somewhat broader than the one used in the pilot.',
   'The findings are highly relevant to services that rely on seasonal staff.'],
  'strongly supports',
  'Dịch sang tiếng Anh: Định nghĩa sửa đổi rộng hơn một phần so với định nghĩa dùng trong pilot.',
  'The evidence highly supports a phased implementation.',
  'The evidence strongly supports a phased implementation.',
  'Support collocates naturally with strongly; highly thường bổ nghĩa adjective hoặc một số participle/adverbial combinations.'),
 ('gr.c1.advanced-preposition-choice',
  'Advanced preposition choice is often lexically fixed or meaning-sensitive and cannot be predicted reliably from literal translation.',
  'Lựa chọn giới từ nâng cao thường mang tính từ vựng/collocation hoặc phụ thuộc nghĩa và không thể suy ra chắc chắn bằng dịch sát.',
  ['noun/adjective/verb + conventional preposition', 'preposition choice changes semantic relation'],
  'Learn the preposition with the governing word and verify whether alternative prepositions change meaning or register.',
  ['The committee expressed reservations about the proposed exemption from the reporting requirement.',
   'The new guidance is consistent with the principles set out in the earlier judgment.',
   'There is considerable scope for improvement in how the agency communicates risk.'],
  'reservations about',
  'Dịch sang tiếng Anh: Hướng dẫn mới phù hợp với các nguyên tắc được nêu trong phán quyết trước.',
  'The committee expressed reservations on the proposed exemption from the reporting requirement.',
  'The committee expressed reservations about the proposed exemption from the reporting requirement.',
  'Reservation trong nghĩa nghi ngại/lo ngại thường đi với about; các lựa chọn khác có thể thuộc nghĩa hoặc collocation khác.')]


def sj(value):
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def load(path):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def write(path, value):
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(sj(value), encoding="utf-8")


def digest(record):
    normalized = copy.deepcopy(record)
    checks = normalized.get("quality", {}).get("checks", {})
    checks.pop("cefr", None)
    checks.pop("license", None)
    return hashlib.sha256(sj(normalized).encode()).hexdigest()


def provenance():
    return {"sources": [{"dataset": "project-original", "license": "LicenseRef-Project-Original", "modified": False}]}


def quality(kind):
    checks = {
        "schema": {"status": "pass", "method": "e05-grammar-scale-authoring-v2"},
        "grammar": {"status": "pending", "method": "editor-review-required"},
        "translation": {"status": "pending", "method": "bilingual-review-required"},
        "exactDuplicate": {"status": "pass", "method": "stable-id-and-local-exact-dedup-v1"},
        "nearDuplicate": {"status": "pending", "method": "cross-runtime-near-dedup-review-required"},
        "naturalness": {"status": "pending", "method": "editor-review-required"},
        "cefr": {"status": "pending", "method": "cefr-review-required"},
        "license": {"status": "pending", "method": "project-original-license-review-required"},
    }
    checks["targetStructure" if kind == "mistake" else "targetPresence"] = {
        "status": "pending",
        "method": "linked-content-target-review-required",
    }
    return {"state": "draft", "checks": checks}


def replace_once(text, old, new, label):
    if text.count(old) != 1:
        raise SystemExit(f"{label}: expected one occurrence of {old!r}, got {text.count(old)}")
    return text.replace(old, new, 1)


def build():
    catalog = {item["id"]: item for item in load("content/english/grammar/topic-catalog.json")["topics"]}
    expected_ids = [row[0] for row in R]
    if len(expected_ids) != 48 or len(set(expected_ids)) != 48:
        raise SystemExit("C1 rows must contain exactly 48 unique topics")
    missing_from_catalog = [topic_id for topic_id in expected_ids if topic_id not in catalog]
    if missing_from_catalog:
        raise SystemExit(f"Topics missing from catalog: {missing_from_catalog}")
    wrong_level = [topic_id for topic_id in expected_ids if catalog[topic_id].get("cefr") != "C1"]
    if wrong_level:
        raise SystemExit(f"Topics are not C1 in catalog: {wrong_level}")

    output = []
    for slice_index in range(6):
        rows = R[slice_index * 8 : (slice_index + 1) * 8]
        slice_number = f"{slice_index + 1:02d}"
        paths = {
            "grammar-topics": f"content/english/grammar/e05-scale-c1-{slice_number}-topics.json",
            "examples": f"content/english/sentences/e05-scale-c1-{slice_number}-sentences.json",
            "exercises": f"content/english/sentences/e05-scale-c1-{slice_number}-exercises.json",
            "common-mistakes": f"content/english/sentences/e05-scale-c1-{slice_number}-common-mistakes.json",
        }
        sets = {key: [] for key in paths}
        for position, row in enumerate(rows, 1):
            topic_id, concept_en, concept_vi, formulae, when_to_use, examples, answer, translation_vi, wrong, correct, explanation_vi = row
            base = f"grc1.{slice_number}.{position:02d}"
            sentence_ids = [f"sent.{base}.{number}" for number in (1, 2, 3)]
            exercise_ids = [f"ex.cloze.{base}", f"ex.translation.{base}"]
            mistake_id = f"err.{base}"
            meta = catalog[topic_id]
            if examples[0].count(answer) != 1:
                raise SystemExit(f"{topic_id}: cloze answer {answer!r} must occur exactly once in first example")
            prompt = examples[0].replace(answer, "___", 1)
            sets["grammar-topics"].append({
                "schemaVersion": 1,
                "id": topic_id,
                "cefr": "C1",
                "title": meta["title"],
                "objective": meta["objective"],
                "concept": {"en": concept_en, "vi": concept_vi},
                "formulae": formulae,
                "whenToUse": [when_to_use],
                "forms": {"positive": examples},
                "variations": [],
                "relatedCollocationIds": [],
                "exampleIds": sentence_ids,
                "commonMistakeIds": [mistake_id],
                "contrastTopicIds": [],
                "dialogueIds": [],
                "prerequisiteIds": [],
                "exerciseIds": exercise_ids,
                "quality": quality("topic"),
                "provenance": {
                    "sources": [{
                        "dataset": "project-original",
                        "sourceId": topic_id,
                        "sourceUrl": paths["grammar-topics"],
                        "snapshot": "2026-10",
                        "license": "LicenseRef-Project-Original",
                        "modified": False,
                    }],
                    "note": "Project-original controlled C1 grammar-body content; publication is review-ledger only.",
                },
            })
            for number, text in enumerate(examples):
                sets["examples"].append({
                    "schemaVersion": 1,
                    "id": sentence_ids[number],
                    "text": text,
                    "cefr": "C1",
                    "grammarIds": [topic_id],
                    "quality": quality("example"),
                    "provenance": provenance(),
                })
            sets["exercises"].append({
                "schemaVersion": 1,
                "id": exercise_ids[0],
                "type": "cloze",
                "prompt": prompt,
                "targetIds": [topic_id],
                "acceptedAnswers": [answer],
                "sourceSentenceIds": [sentence_ids[0]],
                "cefr": "C1",
                "quality": quality("exercise"),
                "provenance": provenance(),
            })
            sets["exercises"].append({
                "schemaVersion": 1,
                "id": exercise_ids[1],
                "type": "translation",
                "prompt": translation_vi,
                "targetIds": [topic_id],
                "acceptedAnswers": [examples[1]],
                "sourceSentenceIds": [sentence_ids[1]],
                "cefr": "C1",
                "quality": quality("exercise"),
                "provenance": provenance(),
            })
            sets["common-mistakes"].append({
                "schemaVersion": 1,
                "id": mistake_id,
                "incorrect": wrong,
                "corrections": [correct],
                "explanationVi": explanation_vi,
                "targetIds": [topic_id],
                "evidenceType": "pedagogical",
                "quality": quality("mistake"),
                "provenance": provenance(),
            })
        for set_id, path in paths.items():
            write(path, {"schemaVersion": 1, "records": sets[set_id]})
        output.append((slice_number, paths, sets))
    return output


def add_manifest(slices):
    manifest = load("content/english/batches/manifest.json")
    existing_ids = {batch["id"] for batch in manifest["batches"]}
    new_ids = [f"e05.grammar-scale-c1-{slice_number}" for slice_number, _, _ in slices]
    collision = [batch_id for batch_id in new_ids if batch_id in existing_ids]
    if collision:
        raise SystemExit(f"C1 batch IDs already exist: {collision}")
    insertion = next(index for index, batch in enumerate(manifest["batches"]) if batch["id"] == "e05.grammar-scale-b2-08") + 1
    required_checks = {
        "grammar-topics": ["schema", "grammar", "translation", "exactDuplicate", "nearDuplicate", "naturalness", "targetPresence", "cefr", "license"],
        "examples": ["schema", "grammar", "translation", "exactDuplicate", "nearDuplicate", "naturalness", "targetPresence", "cefr", "license"],
        "exercises": ["schema", "grammar", "translation", "exactDuplicate", "nearDuplicate", "naturalness", "targetPresence", "cefr", "license"],
        "common-mistakes": ["schema", "grammar", "translation", "exactDuplicate", "nearDuplicate", "naturalness", "targetStructure", "cefr", "license"],
    }
    batches = []
    for slice_number, paths, sets in slices:
        batch_id = f"e05.grammar-scale-c1-{slice_number}"
        batches.append({
            "id": batch_id,
            "phase": "E05",
            "category": "grammar",
            "cefr": ["C1"],
            "state": "draft",
            "recordSets": [{
                "id": set_id,
                "path": paths[set_id],
                "expectedCount": len(sets[set_id]),
                "generated": False,
                "allowedQualityStates": ["draft"],
                "requiredChecks": required_checks[set_id],
            } for set_id in ("grammar-topics", "examples", "exercises", "common-mistakes")],
            "requiredBeforePublish": [
                "schema-validation", "reference-integrity", "exact-dedup", "near-dedup",
                "grammar-review", "bilingual-review", "naturalness-review", "cefr-review",
                "target-structure-review", "license-review", "cross-game-smoke",
            ],
            "gameSmokes": [
                {"gameId": "space-typing", "activity": "grammar-challenge", "recordSetId": "grammar-topics", "sampleCount": min(5, len(sets["grammar-topics"]))},
                {"gameId": "monkeytype", "activity": "grammar-topic", "recordSetId": "grammar-topics", "sampleCount": min(5, len(sets["grammar-topics"]))},
                {"gameId": "monkeytype", "activity": "example-typing", "recordSetId": "examples", "sampleCount": min(5, len(sets["examples"]))},
                {"gameId": "monkeytype", "activity": "cloze", "recordSetId": "exercises", "sampleCount": min(4, sum(1 for record in sets["exercises"] if record.get("type") == "cloze")), "recordType": "cloze"},
                {"gameId": "monkeytype", "activity": "translation", "recordSetId": "exercises", "sampleCount": min(4, sum(1 for record in sets["exercises"] if record.get("type") == "translation")), "recordType": "translation"},
                {"gameId": "monkeytype", "activity": "error-correction", "recordSetId": "common-mistakes", "sampleCount": min(4, len(sets["common-mistakes"]))},
            ],
        })
    manifest["batches"][insertion:insertion] = batches
    write("content/english/batches/manifest.json", manifest)


def add_reviews(slices):
    for slice_number, _paths, sets in slices:
        decisions = []
        batch_id = f"e05.grammar-scale-c1-{slice_number}"
        for set_id in ("grammar-topics", "examples", "exercises", "common-mistakes"):
            for record in sets[set_id]:
                checks = {
                    name: {
                        "status": "not-applicable" if check.get("status") == "not-applicable" else "pass",
                        "method": f"editorial-{name}-review-c1-{slice_number}",
                    }
                    for name, check in record["quality"]["checks"].items()
                }
                decisions.append({
                    "id": f"review.e05.c1-{slice_number}." + record["id"].replace(".", "-"),
                    "batchId": batch_id,
                    "recordSetId": set_id,
                    "recordId": record["id"],
                    "sourceDigest": digest(record),
                    "targetState": "published",
                    "checks": checks,
                    "reviewedAt": "2026-10-06T05:20:00Z",
                    "reviewedBy": "GPT-5.6 Sol grammar editorial review",
                    "note": f"Controlled C1 grammar-body slice {slice_number} reviewed for grammar, bilingual meaning, naturalness, target structure, CEFR, dedup and provenance.",
                })
        write(f"content/english/reviews/decisions.d/e05-grammar-c1-{slice_number}.json",
              {"schemaVersion": 1, "decisions": decisions})


def update_counts():
    smoke_path = ROOT / "scripts/smoke-published-english-content.mjs"
    text = smoke_path.read_text(encoding="utf-8")
    replacements = [
        ("grammarManifest.count!==219", "grammarManifest.count!==267"),
        ("219 reviewed grammar topics", "267 reviewed grammar topics"),
        ("sentenceManifest.count!==2902", "sentenceManifest.count!==3190"),
        ("2902 reviewed records", "3190 reviewed records"),
        ("topics.length!==219||examples.length!==1257||exercises.length!==1238||dialogues.length!==100||commonMistakes.length!==307",
         "topics.length!==267||examples.length!==1401||exercises.length!==1334||dialogues.length!==100||commonMistakes.length!==355"),
        ("219 topics + 1257 examples + 1238 exercises + 100 dialogues + 307 common mistakes",
         "267 topics + 1401 examples + 1334 exercises + 100 dialogues + 355 common mistakes"),
        ("monkeyCorrectionCount!==407", "monkeyCorrectionCount!==455"),
        ("100 corrections + 307 common mistakes", "100 corrections + 355 common mistakes"),
        ("monkeyCorrectionRecords:407", "monkeyCorrectionRecords:455"),
    ]
    for old, new in replacements:
        text = replace_once(text, old, new, "C1 final counts")
    smoke_path.write_text(text, encoding="utf-8")

    release = load("content/english/releases/2026.10.0.json")
    release["runtimeCounts"]["grammar"] = 267
    release["runtimeCounts"]["sentences"] = 3190
    release["batchStates"]["draft"] = 67
    write("content/english/releases/2026.10.0.json", release)


def main():
    slices = build()
    add_manifest(slices)
    add_reviews(slices)
    update_counts()
    print(json.dumps({"slices": 6, "topics": 48, "records": 336}, indent=2))


if __name__ == "__main__":
    main()
