#!/usr/bin/env python3
from pathlib import Path
import runpy
ROOT=Path(__file__).resolve().parents[1]; s=runpy.run_path(str(ROOT/'scripts/english-e04-scale-92-common.py'),run_name='e04_scale92_progress'); replace_once=s['replace_once']; path=s['PROGRESS_PATH']; text=path.read_text(encoding='utf-8')
repls=[
('- Latest fully CI-verified scale-up checkpoint before scale-91 publication: `093300e66ee6ff2180e1c06deb0e43fe3c56f324` — scale-90 publication state verified by English Content Master Plan Acceptance #257, English Content Full Validation #212 and Platform CI #1404; published output: `8cfa83802846415de04a1e472d0f40fa1fd7fd58`.','- Latest fully CI-verified scale-up checkpoint before scale-92 publication: `7abb7b4bcf8ecdffd550b41cc04b1c9c5a3e089c` — scale-91 publication state verified by English Content Master Plan Acceptance #260, English Content Full Validation #214 and Platform CI #1407; published output: `ecf0d1cf2589e3a33ebb68337bd137a0327d13fc`.','verified scale-91 checkpoint'),
('- Scale-91 bot publication commit `ecf0d1cf2589e3a33ebb68337bd137a0327d13fc` is complete; the current step is normal-user checkpoint CI verification for that publication state.','- Scale-91 publication checkpoint `7abb7b4bcf8ecdffd550b41cc04b1c9c5a3e089c` is fully verified; scale-92 is the current publication unit.','scale-91 verification state'),
('- E04 phrase/pattern architecture + current reviewed publication: complete — 4,390 published records after scale-91','- E04 phrase/pattern architecture + current reviewed publication: complete — 4,430 published records after scale-92','E04 publication count'),
('## Published runtime snapshot after E04 scale-91 publication','## Published runtime snapshot after E04 scale-92 publication','runtime heading'),
('- phrases: 4,390 records','- phrases: 4,430 records','phrase count'),
('- total published rich records: 8,991','- total published rich records: 9,031','rich count'),
('- editorial ledger: 8,991 decisions / 8,991 applied / 8,991 publish decisions','- editorial ledger: 9,031 decisions / 9,031 applied / 9,031 publish decisions','ledger count'),
('- E04 collocation frontier: `col.00003280`','- E04 collocation frontier: `col.00003320`','frontier'),
('1. Scale-90 publication is fully verified at `093300e66ee6ff2180e1c06deb0e43fe3c56f324`; do not duplicate scale-90 artifacts.','1. Scale-91 publication is fully verified at `7abb7b4bcf8ecdffd550b41cc04b1c9c5a3e089c`; do not duplicate scale-91 artifacts.','verified workstream'),
('2. Scale-91 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','2. Scale-92 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','current workstream'),
('3. After the scale-91 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','3. After the scale-92 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','checkpoint workstream'),
('5. If no safer pending enrichment appears after the scale-91 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00003280`, expected IDs `col.00003281`–`col.00003320`, with fresh exact/near-dedupe preflight before any source apply.','5. If no safer pending enrichment appears after the scale-92 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00003320`, expected IDs `col.00003321`–`col.00003360`, with fresh exact/near-dedupe preflight before any source apply.','next batch'),
('Scale-91 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00003280` (expected next range `col.00003281`–`col.00003320`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','Scale-92 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00003320` (expected next range `col.00003321`–`col.00003360`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','next task')]
for old,new,label in repls: text=replace_once(text,old,new,label)
path.write_text(text,encoding='utf-8')
