#!/usr/bin/env python3
from pathlib import Path
import runpy
ROOT=Path(__file__).resolve().parents[1]; s=runpy.run_path(str(ROOT/'scripts/english-e04-scale-122-common.py'),run_name='e04_scale122_progress'); replace_once=s['replace_once']; path=s['PROGRESS_PATH']; text=path.read_text(encoding='utf-8')
repls=[
('- Latest fully CI-verified scale-up checkpoint before scale-121 publication: `caa492d8cbe8f869d60b7ff1e623e1cf0d902989` — scale-120 publication state verified by English Content Master Plan Acceptance #367, English Content Full Validation #292 and Platform CI #1557; published output: `5a7fbdca01a68d67df391c7e7bfab82ffb47b7dd`.','- Latest fully CI-verified scale-up checkpoint before scale-122 publication: `09bcddd5aaafac2cbdb9baa0d3fb15dcb9658c0b` — scale-121 publication state verified by English Content Master Plan Acceptance #370, English Content Full Validation #294 and Platform CI #1561; published output: `13d53508e15218ef26a99f9d3ced82ab8537411e`.','verified scale-121 checkpoint'),
('- Scale-120 publication checkpoint `caa492d8cbe8f869d60b7ff1e623e1cf0d902989` is fully verified; scale-121 is the current publication unit.','- Scale-121 publication checkpoint `09bcddd5aaafac2cbdb9baa0d3fb15dcb9658c0b` is fully verified; scale-122 is the current publication unit.','scale-121 verification state'),
('- E04 phrase/pattern architecture + current reviewed publication: complete — 5,590 published records after scale-121','- E04 phrase/pattern architecture + current reviewed publication: complete — 5,630 published records after scale-122','E04 publication count'),
('## Published runtime snapshot after E04 scale-121 publication','## Published runtime snapshot after E04 scale-122 publication','runtime heading'),
('- phrases: 5,590 records','- phrases: 5,630 records','phrase count'),
('- total published rich records: 10,191','- total published rich records: 10,231','rich count'),
('- editorial ledger: 10,191 decisions / 10,191 applied / 10,191 publish decisions','- editorial ledger: 10,231 decisions / 10,231 applied / 10,231 publish decisions','ledger count'),
('- E04 collocation frontier: `col.00004480`','- E04 collocation frontier: `col.00004520`','frontier'),
('1. Scale-120 publication is fully verified at `caa492d8cbe8f869d60b7ff1e623e1cf0d902989`; do not duplicate scale-120 artifacts.','1. Scale-121 publication is fully verified at `09bcddd5aaafac2cbdb9baa0d3fb15dcb9658c0b`; do not duplicate scale-121 artifacts.','verified workstream'),
('2. Scale-121 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','2. Scale-122 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','current workstream'),
('3. After the scale-121 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','3. After the scale-122 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','checkpoint workstream'),
('5. If no safer pending enrichment appears after the scale-121 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00004480`, expected IDs `col.00004481`–`col.00004520`, with fresh exact/near-dedupe preflight before any source apply.','5. If no safer pending enrichment appears after the scale-122 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00004520`, expected IDs `col.00004521`–`col.00004560`, with fresh exact/near-dedupe preflight before any source apply.','next batch'),
('Scale-121 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00004480` (expected next range `col.00004481`–`col.00004520`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','Scale-122 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00004520` (expected next range `col.00004521`–`col.00004560`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','next task')]
for old,new,label in repls: text=replace_once(text,old,new,label)
path.write_text(text,encoding='utf-8')
