#!/usr/bin/env python3
from pathlib import Path
import runpy
ROOT=Path(__file__).resolve().parents[1]; s=runpy.run_path(str(ROOT/'scripts/english-e04-scale-94-common.py'),run_name='e04_scale94_progress'); replace_once=s['replace_once']; path=s['PROGRESS_PATH']; text=path.read_text(encoding='utf-8')
repls=[
('- Latest fully CI-verified scale-up checkpoint before scale-93 publication: `7f5e26fab38aedaa725fcbbc6e69b8d877cad14f` — scale-92 publication state verified by English Content Master Plan Acceptance #264, English Content Full Validation #217 and Platform CI #1411; published output: `ea7f5382af0bb8d2f2dcf07f899f491fd1aa3c9d`.','- Latest fully CI-verified scale-up checkpoint before scale-94 publication: `3d04dac534875eb02048e25b4411d84714ae3c51` — scale-93 publication state verified by English Content Master Plan Acceptance #268, English Content Full Validation #220 and Platform CI #1415; published output: `17c49d0e7b82873840545df68feb9e8f6ca154bf`.','verified scale-93 checkpoint'),
('- Scale-93 bot publication commit `17c49d0e7b82873840545df68feb9e8f6ca154bf` is complete; the current step is normal-user checkpoint CI verification for that publication state.','- Scale-93 publication checkpoint `3d04dac534875eb02048e25b4411d84714ae3c51` is fully verified; scale-94 is the current publication unit.','scale-93 verification state'),
('- E04 phrase/pattern architecture + current reviewed publication: complete — 4,470 published records after scale-93','- E04 phrase/pattern architecture + current reviewed publication: complete — 4,510 published records after scale-94','E04 publication count'),
('## Published runtime snapshot after E04 scale-93 publication','## Published runtime snapshot after E04 scale-94 publication','runtime heading'),
('- phrases: 4,470 records','- phrases: 4,510 records','phrase count'),
('- total published rich records: 9,071','- total published rich records: 9,111','rich count'),
('- editorial ledger: 9,071 decisions / 9,071 applied / 9,071 publish decisions','- editorial ledger: 9,111 decisions / 9,111 applied / 9,111 publish decisions','ledger count'),
('- E04 collocation frontier: `col.00003360`','- E04 collocation frontier: `col.00003400`','frontier'),
('1. Scale-92 publication is fully verified at `7f5e26fab38aedaa725fcbbc6e69b8d877cad14f`; do not duplicate scale-92 artifacts.','1. Scale-93 publication is fully verified at `3d04dac534875eb02048e25b4411d84714ae3c51`; do not duplicate scale-93 artifacts.','verified workstream'),
('2. Scale-93 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','2. Scale-94 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','current workstream'),
('3. After the scale-93 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','3. After the scale-94 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','checkpoint workstream'),
('5. If no safer pending enrichment appears after the scale-93 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00003360`, expected IDs `col.00003361`–`col.00003400`, with fresh exact/near-dedupe preflight before any source apply.','5. If no safer pending enrichment appears after the scale-94 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00003400`, expected IDs `col.00003401`–`col.00003440`, with fresh exact/near-dedupe preflight before any source apply.','next batch'),
('Scale-93 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00003360` (expected next range `col.00003361`–`col.00003400`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','Scale-94 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00003400` (expected next range `col.00003401`–`col.00003440`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','next task')]
for old,new,label in repls: text=replace_once(text,old,new,label)
path.write_text(text,encoding='utf-8')
