#!/usr/bin/env python3
from pathlib import Path
import runpy
ROOT=Path(__file__).resolve().parents[1]; s=runpy.run_path(str(ROOT/'scripts/english-e04-scale-96-common.py'),run_name='e04_scale96_progress'); replace_once=s['replace_once']; path=s['PROGRESS_PATH']; text=path.read_text(encoding='utf-8')
repls=[
('- Latest fully CI-verified scale-up checkpoint before scale-95 publication: `dec3a4bc6acedc2f7f8cd7fc3abad23430aded66` — scale-94 publication state verified by English Content Master Plan Acceptance #273, English Content Full Validation #224 and Platform CI #1420; published output: `1493a59ecd90fd7be76507d5bc1a196270f0fa43`.','- Latest fully CI-verified scale-up checkpoint before scale-96 publication: `cb2f24f492f141f38f04e2725a162691548846ef` — scale-95 publication state verified by English Content Master Plan Acceptance #276, English Content Full Validation #226 and Platform CI #1423; published output: `34fd31d8add24592ef5f056664861aeb0f47d881`.','verified scale-95 checkpoint'),
('- Scale-95 bot publication commit `34fd31d8add24592ef5f056664861aeb0f47d881` is complete; the current step is normal-user checkpoint CI verification for that publication state.','- Scale-95 publication checkpoint `cb2f24f492f141f38f04e2725a162691548846ef` is fully verified; scale-96 is the current publication unit.','scale-95 verification state'),
('- E04 phrase/pattern architecture + current reviewed publication: complete — 4,550 published records after scale-95','- E04 phrase/pattern architecture + current reviewed publication: complete — 4,590 published records after scale-96','E04 publication count'),
('## Published runtime snapshot after E04 scale-95 publication','## Published runtime snapshot after E04 scale-96 publication','runtime heading'),
('- phrases: 4,550 records','- phrases: 4,590 records','phrase count'),
('- total published rich records: 9,151','- total published rich records: 9,191','rich count'),
('- editorial ledger: 9,151 decisions / 9,151 applied / 9,151 publish decisions','- editorial ledger: 9,191 decisions / 9,191 applied / 9,191 publish decisions','ledger count'),
('- E04 collocation frontier: `col.00003440`','- E04 collocation frontier: `col.00003480`','frontier'),
('1. Scale-94 publication is fully verified at `dec3a4bc6acedc2f7f8cd7fc3abad23430aded66`; do not duplicate scale-94 artifacts.','1. Scale-95 publication is fully verified at `cb2f24f492f141f38f04e2725a162691548846ef`; do not duplicate scale-95 artifacts.','verified workstream'),
('2. Scale-95 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','2. Scale-96 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','current workstream'),
('3. After the scale-95 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','3. After the scale-96 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','checkpoint workstream'),
('5. If no safer pending enrichment appears after the scale-95 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00003440`, expected IDs `col.00003441`–`col.00003480`, with fresh exact/near-dedupe preflight before any source apply.','5. If no safer pending enrichment appears after the scale-96 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00003480`, expected IDs `col.00003481`–`col.00003520`, with fresh exact/near-dedupe preflight before any source apply.','next batch'),
('Scale-95 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00003440` (expected next range `col.00003441`–`col.00003480`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','Scale-96 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00003480` (expected next range `col.00003481`–`col.00003520`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','next task')]
for old,new,label in repls: text=replace_once(text,old,new,label)
path.write_text(text,encoding='utf-8')
