#!/usr/bin/env python3
from pathlib import Path
import runpy
ROOT=Path(__file__).resolve().parents[1]; s=runpy.run_path(str(ROOT/'scripts/english-e04-scale-98-common.py'),run_name='e04_scale98_progress'); replace_once=s['replace_once']; path=s['PROGRESS_PATH']; text=path.read_text(encoding='utf-8')
repls=[
('- Latest fully CI-verified scale-up checkpoint before scale-97 publication: `39ee87e69621aa1b34cf362a83479330ea6208e4` — scale-96 publication state verified by English Content Master Plan Acceptance #279, English Content Full Validation #228 and Platform CI #1430; published output: `29b6507fde5e65c2dc7638d0f3a4a828c08830b6`.','- Latest fully CI-verified scale-up checkpoint before scale-98 publication: `841af2d9ffeace8a5b28d0ea8023bfe40130665c` — scale-97 publication state verified by English Content Master Plan Acceptance #283, English Content Full Validation #231 and Platform CI #1434; published output: `b5aab1e54affc77b8e9d839ec979ef16e4497522`.','verified scale-97 checkpoint'),
('- Scale-97 bot publication commit `b5aab1e54affc77b8e9d839ec979ef16e4497522` is complete; the current step is normal-user checkpoint CI verification for that publication state.','- Scale-97 publication checkpoint `841af2d9ffeace8a5b28d0ea8023bfe40130665c` is fully verified; scale-98 is the current publication unit.','scale-97 verification state'),
('- E04 phrase/pattern architecture + current reviewed publication: complete — 4,630 published records after scale-97','- E04 phrase/pattern architecture + current reviewed publication: complete — 4,670 published records after scale-98','E04 publication count'),
('## Published runtime snapshot after E04 scale-97 publication','## Published runtime snapshot after E04 scale-98 publication','runtime heading'),
('- phrases: 4,630 records','- phrases: 4,670 records','phrase count'),
('- total published rich records: 9,231','- total published rich records: 9,271','rich count'),
('- editorial ledger: 9,231 decisions / 9,231 applied / 9,231 publish decisions','- editorial ledger: 9,271 decisions / 9,271 applied / 9,271 publish decisions','ledger count'),
('- E04 collocation frontier: `col.00003520`','- E04 collocation frontier: `col.00003560`','frontier'),
('1. Scale-96 publication is fully verified at `39ee87e69621aa1b34cf362a83479330ea6208e4`; do not duplicate scale-96 artifacts.','1. Scale-97 publication is fully verified at `841af2d9ffeace8a5b28d0ea8023bfe40130665c`; do not duplicate scale-97 artifacts.','verified workstream'),
('2. Scale-97 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','2. Scale-98 is the current publication unit; do not start another collocation batch until its publication/checkpoint CI completes.','current workstream'),
('3. After the scale-97 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','3. After the scale-98 bot publication commit is created, create exactly one normal-user checkpoint and verify English Content Full Validation, Master Plan Acceptance and Platform CI.','checkpoint workstream'),
('5. If no safer pending enrichment appears after the scale-97 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00003520`, expected IDs `col.00003521`–`col.00003560`, with fresh exact/near-dedupe preflight before any source apply.','5. If no safer pending enrichment appears after the scale-98 checkpoint, continue with a bounded E04 collocation batch from frontier `col.00003560`, expected IDs `col.00003561`–`col.00003600`, with fresh exact/near-dedupe preflight before any source apply.','next batch'),
('Scale-97 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00003520` (expected next range `col.00003521`–`col.00003560`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','Scale-98 is the current publication unit. After its bot publication commit is created, verify remote HEAD and create exactly one normal-user checkpoint. If all mandatory CI PASS, continue immediately with the next genuinely new bounded collocation batch from frontier `col.00003560` (expected next range `col.00003561`–`col.00003600`, unless a safer under-target E04 family takes priority). Recalculate counts and run exact/near dedupe before every write.','next task')]
for old,new,label in repls: text=replace_once(text,old,new,label)
path.write_text(text,encoding='utf-8')
